### ISSUE TITLE
[Bug] After updating, the following error causes Import Failed:  ModuleNotFoundError: No module named 'nvdiffrast'

### ISSUE THREAD

**Issue by ricardofeynman** [MrForExample/ComfyUI-3D-Pack#1]
Thanks for releasing this. Looking forward to testing it out.

I had installed earlier and got no error mesages, however after updating to Commit 4 [0d5e579] a couple hours ago, the following error appears:

Traceback (most recent call last):
  File "/blah/ComfyUI/nodes.py", line 1810, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/blah/ComfyUI/custom_nodes/ComfyUI-3D-Pack/__init__.py", line 8, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/blah/miniconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/blah/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 6, in <module>
    from .diff_rast.diff_texturing import DiffTextureBaker
  File "/blah/ComfyUI/custom_nodes/ComfyUI-3D-Pack/diff_rast/diff_texturing.py", line 8, in <module>
    from ..diff_rast.diff_mesh_renderer import Renderer
  File "/blah/ComfyUI/custom_nodes/ComfyUI-3D-Pack/diff_rast/diff_mesh_renderer.py", line 8, in <module>
    import nvdiffrast.torch as dr
ModuleNotFoundError: No module named 'nvdiffrast'

Cannot import /blah/ComfyUI/custom_nodes/ComfyUI-3D-Pack module for custom nodes: No module named 'nvdiffrast'

I tried 'pip install nvdiffrast' but got the follwing response:

ERROR: Could not find a version that satisfies the requirement nvdiffrast (from versions: none)
ERROR: No matching distribution found for nvdiffrast

I'm guessing it could be something to do with a torch version conflict, I am using (and require) version 2.1.2 for several other custom nodes. I tried uninstalling and doing a fresh install via the manager and the issue persists.

Any ideas?

**Comment by MrForExample** [comment]
Sorry my friend, this is project is still a working progress, you are right, so far I only manage to make it work inside Miniconda/Conda environment with cuda 11.8 and corresponding torch version. 
Last version of nvdiffrast is updated 7 months ago and I couldn't find out why I can't build it with ComfyUI's embed python env.
I'll see if I can make it work today, and update document.

Thanks for testing, and apologies again for the trouble, let's work together to bring the best 3D AI Tools for everyone :)

**Comment by MrForExample** [comment]
Hi friend, it is working now with both torch version 2.1.2 + cuda 121 / 118, Minicond Python 3.11

I also updated the readme and include some example workflow with input data, you are welcome to give a another try anytime 👍

**Comment by xiwan** [comment]
```
!git clone --recursive https://github.com/NVlabs/nvdiffrast
!git clone --recursive https://github.com/graphdeco-inria/gaussian-splatting

%cd  path/to/nvdiffrast
!pip install .

%cd path/to/gaussian-splatting
!pip install submodules/diff-gaussian-rasterization
!pip install submodules/simple-knn
```

will fix the issue

**Comment by BoosterCore** [comment]
> ```
> !git clone --recursive https://github.com/NVlabs/nvdiffrast
> !git clone --recursive https://github.com/graphdeco-inria/gaussian-splatting
> 
> %cd  path/to/nvdiffrast
> !pip install .
> 
> %cd path/to/gaussian-splatting
> !pip install submodules/diff-gaussian-rasterization
> !pip install submodules/simple-knn
> ```
> 
> will fix the issue

Is this approach possible for the Portable version?

**Comment by ricardofeynman** [comment]
@MrForExample I've just spotted this, thanks! Will give the update a try later today, and let you know how I'm getting on with the latest commit. 

Really excited to see what I can do with this, been getting very interested in gaussian splatting again recently, especially 4D gaussian splatting for realtime use. 

Any chance of a ComfyUI-4D-Pack next....? ;D

**Comment by MrForExample** [comment]
> > ```
> > !git clone --recursive https://github.com/NVlabs/nvdiffrast
> > !git clone --recursive https://github.com/graphdeco-inria/gaussian-splatting
> > 
> > %cd  path/to/nvdiffrast
> > !pip install .
> > 
> > %cd path/to/gaussian-splatting
> > !pip install submodules/diff-gaussian-rasterization
> > !pip install submodules/simple-knn
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > will fix the issue
> 
> Is this approach possible for the Portable version? 
 
From what I tested, not work on Windows, I got CUDA build error with that, still don't know how to solve it, but maybe it was because I have too many packages installed on my PC, so you are welcome to give a try though 👍

**Comment by MrForExample** [comment]
> @MrForExample I've just spotted this, thanks! Will give the update a try later today, and let you know how I'm getting on with the latest commit.
> 
> Really excited to see what I can do with this, been getting very interested in gaussian splatting again recently, especially 4D gaussian splatting for realtime use.
> 
> Any chance of a ComfyUI-4D-Pack next....? ;D

Haha, I was waiting for something like this that allow this kind of Modular free combination for 3D gen AI for a few months now, seems most researchers are too busy to build their own awesome research, design their own pipeline, nobody really want spent some effort to make it easier for everyday user, so I decide to do it myself.

 ComfyUI-4D-Pack!!! Well, let's do one step at time, I also want to add some text to 3D-Animation in to ComfyUI.
But if past eight years of experience taught me anything then is that: seems slow but steady is always faster than looks fast but flashy. I'm still trying to identify the best use case for this tool, because there are so many direction I could go really deep, it would be completely waste of effort if I chosen the wrong one 👍
