### ISSUE TITLE
No module named 'open_clip'

### ISSUE THREAD

**Issue by popedead** [MrForExample/ComfyUI-3D-Pack#101]
my error at run  CRM_Img_to_Multi-views_to_CCMs_to_Mesh.json

File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\crm\imagedream\ldm\modules\encoders\modules.py", line 8, in <module>
    import open_clip
ModuleNotFoundError: No module named 'open_clip'

and "pip install open_clip_torch", it doesn't fix anything

**Comment by MrForExample** [comment]
If you are using Miniconda env then `pip install --force-reinstall open_clip_torch` will fix it

If you are using comfyUI python embed environment then using "Path to your comfyUI python.exe -s -m pip install --force-reinstall open_clip_torch"

**Comment by popedead** [comment]
working! thanx
"C:\AI\ComfyUI\python_embeded\python.exe" -m pip install --force-reinstall open_clip_torch (on windows)
