### ISSUE TITLE
environmental problems

### ISSUE THREAD

**Issue by wjj2301717059** [MrForExample/ComfyUI-3D-Pack#106]
could give me you delvelop environmental list and python version,i can'nt find pytorch3d wheel for python 3.11

**Comment by MrForExample** [comment]
Hi @wjj2301717059 , I build the [pytorch3d wheel for python 3.11 here](https://github.com/MrForExample/ComfyUI-3D-Pack/tree/main/_Wheels_win_py311_cu121)

**Comment by wjj2301717059** [comment]
thanks,
