### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by if-ai** [MrForExample/ComfyUI-3D-Pack#108]
all goes well till the convolutional reconstruction model then I get this
 ```
[Comfy3D] [Load_CRM_MVDiffusion_Model] loaded model ckpt from /home/impactframes/ComfyUI/custom_nodes/ComfyUI-3D-Pack/checkpoints/crm/ccm-diffusion.pth
DDIM Sampler: 100%|█████████████████████████████████████████████████████████████████████| 50/50 [00:06<00:00,  8.12it/s]
[Comfy3D] [WARNING] [Load_Convolutional_Reconstruction_Model] can't find checkpoint /home/impactframes/ComfyUI/custom_nodes/ComfyUI-3D-Pack/checkpoints/crm/CRM.pth, will download it from repo Zhengyi/CRM instead
CRM.pth: 100%|███████████████████████████████████████████████████████████████████████| 476M/476M [00:56<00:00, 8.40MB/s]
Segmentation fault
```
  probably a memory error I am running on WSL python 3.11.8  cuda 12.4

**Comment by MrForExample** [comment]
Hi seems that's issue [from Python itself](https://stackoverflow.com/questions/10035541/what-causes-a-python-segmentation-fault), one thing you could try is to fresh install a Python 3.11.8-dev and copy /include /libs folders into your ComfyUI python directory i.e. where your python.exe.

**Comment by if-ai** [comment]
Thank you, I am on WSL but I think I will try using the recommendations from the link you shared thanks.
