### ISSUE TITLE
why do you give us picture can produce?but my picture can'nt produce.

### ISSUE THREAD

**Issue by wjj2301717059** [MrForExample/ComfyUI-3D-Pack#109]
![H O`IE@W)HPB9%`KL8O~Q1N](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/99034663/e1f67f4f-65dc-4063-9509-2a5366537629)
![V6OUXG2D9N%L%5(Y1JJ~5$F](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/99034663/ae91cfd7-face-434b-a08c-91c64804ab3e)
if you can give me help i would appreciate it

**Comment by MrForExample** [comment]
Hi @wjj2301717059 
This is a same issue as [99](https://github.com/MrForExample/ComfyUI-3D-Pack/issues/99)
