### ISSUE TITLE
Images limit on Multi-View-Images_to_3DGS_to_3DMesh(DMTet and DiffRast)

### ISSUE THREAD

**Issue by DenisKochetov** [MrForExample/ComfyUI-3D-Pack#117]
Am I obligated to use only 120 images? 
`Comfy3D] [ERROR] [Gaussian_Splatting] Number of reference images 259 does not equal to number of reference camera poses 120
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 316, in switch_axis_and_scale
    switched_gs_ply = switch_ply_axis_and_scale(gs_ply, target_axis, target_scale, coordinate_invert_count)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-3D-Pack/mesh_processer/mesh_utils.py", line 428, in switch_ply_axis_and_scale
    xyz, features_dc, features_extra, opacities, scales, rots = read_gs_ply(plydata)
                                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-3D-Pack/mesh_processer/mesh_utils.py", line 338, in read_gs_ply
    xyz = np.stack((np.asarray(plydata.elements[0]["x"]),
                               ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'elements'`

**Comment by MrForExample** [comment]
Of course not friend, you have to change the parameters of Stack Orbit Camera Poses to generate camera poses for your reference images

But please note currently there is no camera pose estimation inside Comfy3D yet, so random multi-views images with unknow camera poses will not work
Actually my plan for this week and next is to focus on massive improve MVS algorithms, so we can generate from any 3D model from SV3D multi-views

Cheers, have a good day 👍

**Comment by DenisKochetov** [comment]
Thank you!

**Comment by einstein33** [comment]
I have also encountered this problem, and I would like to ask how to solve it later and how to operate it specifically
