### ISSUE TITLE
Suggestion: Using pre-built PyTorch Scatter from its official

### ISSUE THREAD

**Issue by YanWenKun** [MrForExample/ComfyUI-3D-Pack#137]
As described in the [PyTorch Scatter's doc](https://github.com/rusty1s/pytorch_scatter?tab=readme-ov-file#binaries), instead of compile-install, we can install its official binaries:

```
python3 -m pip install \
  torch-scatter --find-links https://data.pyg.org/whl/torch-2.2.2+cu121.html
```

I guess maybe we could change the item in `requirements_post.txt` ? I mean, building PyTorch Scatter is really slow...

**Comment by MrForExample** [comment]
Yeah, I'll take it look and change it in the next update. cheers👍
