### ISSUE TITLE
Point Cloud Optimization

### ISSUE THREAD

**Issue by v4r4rth** [MrForExample/ComfyUI-3D-Pack#14]
Hi - I decided to move the issues to a new thread as the last one was mostly just me figuring out how to play with your nodes!
I did manage to improve the quality of the splat by refining some parameters but the point cloud itself is not optimised for marching tetrahedrons - below I show the splat, along with the point cloud and generated mesh (without texture) -

![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/149033251/a570bda2-9574-4000-9077-2025076c0611)

My question is, can we find a way to remove the points which are not contributing to the RGB values? Specifically, can we eliminate the Alpha value points from the cloud?

I also came across and implemented this project, [SuGaR ](https://github.com/Anttwo/SuGaR) (check [this issue](https://github.com/Anttwo/SuGaR/issues/75)) which also suggests a method to extract textures and meshes from Gaussian Splatting which is very efficient (tested on provided and my own datasets) - I do hope you take a look once because it did work very well at extracting meshes from gaussian splats :) - The UV Maps were bad, but still, the quality was decent.

**Comment by watsieboi** [comment]
I ran into the same issue - my janky approach to solving was to add a remove background node (https://github.com/Jcd1230/rembg-comfyui-node) after the Zero123 image generation step. Then in the gaussian splatting workflow the image masks will actually be populated and the black background will not contribute to the splats.

**Comment by MrForExample** [comment]
Thanks for the effort friend, I am aware of [SuGaR](https://github.com/Anttwo/SuGaR), and will definitely take a closer look at their method.
I also adopted a better 3DGS to Mesh Conversion Algorithm in yesterday's update, it use nerf to fit 3DGS and then using marching cube to produce mesh & texture by fitting the nerf, and it works much better & faster, feel free to give a try
