### ISSUE TITLE
TripoSR problem

### ISSUE THREAD

**Issue by 807502278** [MrForExample/ComfyUI-3D-Pack#148]
After saving the mesh generated by TripoSR, there are no UVs and textures, but the "Preview 3DMesh" node displays normally.How do I need to save the mesh generated by TripoSR correctly?

**Comment by MrForExample** [comment]
Hi TripoSR has no UVs and textures, it output mesh with vertex colors

**Comment by 807502278** [comment]
Thank you for informing me. I saw it in the 3D software

**Comment by 807502278** [comment]
Thank you for notifying me. I saw colors in the 3D software

**Comment by yosun** [comment]
is there a way to do a bake vertex to texture module on comfyui
