### ISSUE TITLE
Cat3D

### ISSUE THREAD

**Issue by hypervoxel** [MrForExample/ComfyUI-3D-Pack#150]
Love to see this integrated in Comfy if the code is open sourced.

https://cat3d.github.io/

**Comment by MrForExample** [comment]
Yeah, me too, if result is good enough after I test it then I'll add it 👍

**Comment by hypervoxel** [comment]
That would be amazing! I didn't realize they had released the code

**Comment by MrForExample** [comment]
@hypervoxel No they didn't yet, I'm just saying if they ever did, then I'll test it :) Sorry for make it sounds clear
