### ISSUE TITLE
Functional suggestions

### ISSUE THREAD

**Issue by 807502278** [MrForExample/ComfyUI-3D-Pack#156]
This plugin is very useful for 3D, thank you for the author's contribution!
I work in the field of 3D, and I'm sorry that I can't help you with programming. Here are some specific suggestions:

Important:
1:**Increase model face reduction optimization**(for example, the simplest one is to input a threshold to weld adjacent vertices)
as these algorithms generate too many model faces (approximately 30000-8000), and calculating UV will consume a lot of time

2:**Individual UV calculation nodes**(gly texture mapping can be used as an option，All other nodes do not need to calculate UV)
UV can be calculated in any mesh process, and different UV algorithms can be chosen to greatly improve flexibility and avoid calculating UV for high face models.

Less important:
3: hope the preview node can input mesh instead of path, which can avoid saving a large number of useless files.
4:Quadrilateral mesh topology.

Bug:
1:When saving, the texture cannot overwrite the save.

**Comment by MrForExample** [comment]
Hi @807502278 Thank you for your suggestions, I'll add them into my notes about future development, cheers 👍
