### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by 807502278** [MrForExample/ComfyUI-3D-Pack#161]
Can put the models in **.cache** and **ComfyUI \ custom_modes \ ComfyUI-3D Pack \ checkpoints** into the models folder?
It's really too big

**Comment by MrForExample** [comment]
Yeah, it has been suggested by others, I plan to deal with this and other bugs tomorrow, need to make sure it doesn't break anything, cheers friend 👍

**Comment by 807502278** [comment]
Thank you very much
