### ISSUE TITLE
Implement Unique3D

### ISSUE THREAD

**Issue by hypervoxel** [MrForExample/ComfyUI-3D-Pack#169]
This looks promising and they have released the weights...

https://github.com/AiuniAI/Unique3D

https://wukailu.github.io/Unique3D/

https://huggingface.co/spaces/Wuvin/Unique3D/tree/main/ckpt

**Comment by yosun** [comment]
unique3d seems to be integrated but the generated objs lack image textures in mtl?

**Comment by MrForExample** [comment]
Unique3d using vertex color based generation, that's why you couldn't find textures in .mtl, but you'll find VC value in .obj file :)

**Comment by yosun** [comment]
Is there a comfy Module that converts vertex colors to texture
