### ISSUE TITLE
example workflow issues

### ISSUE THREAD

**Issue by faux123** [MrForExample/ComfyUI-3D-Pack#18]
I've installed this custom node correct and I was able to run the example workflow with Cammy correctly, but when I tried to run another example workflow like this one:  Triplane_Gaussian_Transformers_to_3DGS(DMTet and DiffRast).json

I encountered the following errors:

[ERROR] An error occurred while retrieving information for the '[Comfy3D] Load Large Multiview Gaussian Model' node.
Traceback (most recent call last):
  File "G:\3DComfyUI\ComfyUI\server.py", line 420, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "G:\3DComfyUI\ComfyUI\server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\3DComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 1211, in INPUT_TYPES
    "model_name": (get_list_filenames(os.path.join(ROOT_PATH, cls.checkpoints_dir)), ),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\3DComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\shared_utils\common_utils.py", line 122, in get_list_filenames
    return [f for f in listdir(directory) if isfile(join(directory, f)) and (extension_filter is None or f.lower().endswith(extension_filter))]
                       ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\3DComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-3D-Pack\\checkpoints/lgm'
[ERROR] An error occurred while retrieving information for the '[Comfy3D] Load Triplane Gaussian Transformers' node.
Traceback (most recent call last):
  File "G:\3DComfyUI\ComfyUI\server.py", line 420, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "G:\3DComfyUI\ComfyUI\server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\3DComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 1013, in INPUT_TYPES
    "model_name": (get_list_filenames(os.path.join(ROOT_PATH, cls.checkpoints_dir)), ),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\3DComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\shared_utils\common_utils.py", line 122, in get_list_filenames
    return [f for f in listdir(directory) if isfile(join(directory, f)) and (extension_filter is None or f.lower().endswith(extension_filter))]
                       ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\3DComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-3D-Pack\\checkpoints/tgs'

It seems like I'm missing a model/checkpoint.. related to Triplane Gaussian Transformers.. Could you point me to where to download the exact model/checkpoint needed for this.. thanks

**Comment by faux123** [comment]
I figured it out.. you go to here: https://huggingface.co/VAST-AI/TriplaneGaussian/tree/main to download the checkpoint and put the model into 

ComfyUI\custom_nodes\ComfyUI-3D-Pack\checkpoints\tgs folder.

**Comment by MrForExample** [comment]
Glad you figured it out
If you don't have the checkpoint then it should download automatically, ok, maybe a bug, I'll take a look

**Comment by MrForExample** [comment]
Ok, it's an edge case I didn't take into consideration, this issue will be fixed in the next update
