### ISSUE TITLE
Error on RunPod - eglInitialize() failed

### ISSUE THREAD

**Issue by 1halfplusminus** [MrForExample/ComfyUI-3D-Pack#183]
Hi,

I've encountered an issue with ComfyUI-3D-Pack when running it on a RunPod instance. This setup was working previously (when InstantMesh was added), but now it's failing. Here are the details:

Issue Description
When ComfyUI-3D-Pack is enabled, ComfyUI fails to start due to an EGL initialization error:

[F glutil.cpp:338] eglInitialize() failed

Importantly, ComfyUI runs without issues when I disable ComfyUI-3D-Pack. This indicates that the problem is specifically related to this extension.

Environment
Platform: RunPod
OS: Linux
GPU: NVIDIA RTX A6000
Python: 3.11.9
PyTorch: 2.2.2+cu121
Docker Image: Default RunPod image with CUDA 12 and Python 3.10 (runpod/pytorch:2.1.1-py3.10-cuda12.1.1-devel-ubuntu22.04)
Note: This setup was working previously with the same Docker image and configuration.

Questions
Is it normal that ComfyUI-3D-Pack is trying to initialize EGL at the launch of ComfyUI?
The error probably comes from nvdiffrast, and I saw a fix in the Docker image in this repository. However, I can't really change the image or the Docker configuration. Are there any workarounds or alternative solutions you can suggest?
I'd appreciate any insights or workarounds you can provide. Let me know if you need any additional information from my setup.

Thank you for your time and assistance!

**Comment by 1halfplusminus** [comment]
I am closing this issue as it does not directly stem from the ComfyUI-3D-Pack itself. The problem originates from  module that uses nvdiffrast with dr.RasterizeGLContext. The ComfyUI-3D-Pack requires an environment where both CUDA and OpenGL are functional. The default RunPod image only includes the CUDA driver, and it is not possible to install the OpenGL driver inside the container. Therefore, the package only works in environments where both CUDA and OpenGL are supported, which is not the case with the default RunPod image.

**Comment by 1halfplusminus** [comment]
I forked the project and replaced all instances of RasterizeGLContext that were not in an if condition checking if CUDA is installed with RasterizeCudaContext. There are like three places to do it 😂

**Comment by BennyKok** [comment]
Oh man, you are a lifesaver! @1halfplusminus how did you figure that out, i just got it installed successfully, and now I'm trying to actually run it. Also i notice the start time takes around 60 seconds on modal, hows you 3d pack cold start time on runpod?
