### ISSUE TITLE
Lower part of the model extrudes in a strange way using Unique3D

### ISSUE THREAD

**Issue by Moj-X** [MrForExample/ComfyUI-3D-Pack#185]
Thanks so much for implementing all these ways to generate 3d models, by the way. Seriously impressive work.

My issue is when using the `Unique3D_All_Stages` workflow and a character portrait image that extends to the bottom of the frame.

Input image:
![ComfyUI_01317_ alpha_masked](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/61998457/7952ea86-11bd-4b00-95f9-c4f426901225)

Extruded mesh:
<img width="467" alt="extrude_front" src="https://github.com/MrForExample/ComfyUI-3D-Pack/assets/61998457/a63cdf81-3829-4cea-ab3d-d7fad0b8ec31">

<img width="931" alt="Screenshot 2024-07-02 204025" src="https://github.com/MrForExample/ComfyUI-3D-Pack/assets/61998457/3f785a58-a7eb-4294-8df7-9eb76452b7e6">

**Comment by Moj-X** [comment]
I tried masking out more of the lower part of the image to see if that would help but things are just as bad...

<img width="1682" alt="mask_more" src="https://github.com/MrForExample/ComfyUI-3D-Pack/assets/61998457/36fb5767-2ef8-488f-9045-8de765c9d9aa">

**Comment by Moj-X** [comment]
Using the `Mario_Cat.png` does the same thing. Although I did notice that there's a gap at the top and bottom of the first image. I suppose an issue with combining the upscaled input image with the 3 multiview image batch.

<img width="1654" alt="cat_fail" src="https://github.com/MrForExample/ComfyUI-3D-Pack/assets/61998457/a29711ed-3a23-4b93-9789-1fe82d9e08e1">

Notice the gap:
<img width="586" alt="smaller_image" src="https://github.com/MrForExample/ComfyUI-3D-Pack/assets/61998457/5864523a-1e4a-41f1-9d3d-db884eb59786">

**Comment by Moj-X** [comment]
Okay, turning off `preprocess_images` in Stage_1 fixed that issue. But now I just need to clean up the next issue 😬 

<img width="491" alt="pre_process_off" src="https://github.com/MrForExample/ComfyUI-3D-Pack/assets/61998457/e59af3dc-6b82-4d77-8f9b-080f28925f32">

<img width="1631" alt="no_preprocess" src="https://github.com/MrForExample/ComfyUI-3D-Pack/assets/61998457/9070bc05-1705-4c08-88ae-a00f2d94847c">

**Comment by Moj-X** [comment]
Okay, it's still not working.

<img width="1673" alt="still_extruded" src="https://github.com/MrForExample/ComfyUI-3D-Pack/assets/61998457/b3221e12-95d7-43ed-b3bf-8ea8f7d7f147">

**Comment by MrForExample** [comment]
Yeah, that surface discontinuity issue is due to last stage optimization didn't use depth information, it's also mentioned in [this issue](https://github.com/AiuniAI/Unique3D/issues/3)
It will need better mesh reconstruction algorithm to fix that.

**Comment by Moj-X** [comment]
Thanks for the quick reply! So it's a Unique3D specific issue. Nuts.
Closing this.
