### ISSUE TITLE
current install conflicts with Visual Studio2022 17.10

### ISSUE THREAD

**Issue by saidthebird** [MrForExample/ComfyUI-3D-Pack#186]
Just like as it is written on the title. I had problem installing this 3Dpack. 

First problem occurred when installing with miniconda. It had conflicting xformers and torch versions. I resolved it by manually installing them in the miniconda env. 

Next problem occurred when I received the message corecrt.h was missing. 

I went on and installed C++ build environment with windows10 CRT SDK. the problem persisted. Infact, I wasn't able to progress anyfurther, and was stuck for about a week. 

I tried again by completely removing Visual Studio and did a clean install. Now, the installation says my version of Visual Studio 2022 17.10 is not supported.

I can't seemed to rollback to 17.08 and I am stuck. 

Does anyone have similar issue?

**Comment by saidthebird** [comment]
` FAILED: C:/Users/ironm/AppData/Local/Temp/pip-req-build-pr9eyo8k/build/temp.win-amd64-cpython-311/Release/rasterize_points.obj
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\ironm\AppData\Local\Temp\pip-req-build-pr9eyo8k\build\temp.win-amd64-cpython-311\Release\rasterize_points.obj.d -std=c++17 --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /wd4624 -Xcompiler /wd4067 -Xcompiler /wd4068 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -ID:\AI\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\Lib\site-packages\torch\include -ID:\AI\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\Lib\site-packages\torch\include\torch\csrc\api\include -ID:\AI\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\Lib\site-packages\torch\include\TH -ID:\AI\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -ID:\AI\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\include -ID:\AI\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" -c C:\Users\ironm\AppData\Local\Temp\pip-req-build-pr9eyo8k\rasterize_points.cu -o C:\Users\ironm\AppData\Local\Temp\pip-req-build-pr9eyo8k\build\temp.win-amd64-cpython-311\Release\rasterize_points.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -IC:\Users\ironm\AppData\Local\Temp\pip-req-build-pr9eyo8k\third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.`


getting lists and lists of these reports

**Comment by saidthebird** [comment]
an update. I managed to download previous visual studio version from

**Comment by saidthebird** [comment]
Still saying no corecrt.h....

**Comment by saidthebird** [comment]
![스크린샷 2024-07-03 171727](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/23417238/39bd140b-09c1-4e71-9b7e-478bdd25a51a)

here are the settings for Visual Studio install. 

Any ideas?

**Comment by saidthebird** [comment]
i made some progress, i no longer get corecrt.h error. i had to full unisntall windows and start from scratch. 

now i am getting complier error. 
warnings.warn(f'Error checking compiler version for {compiler}: {error}')

i tried  using python 3.11.5 and 3.11.9

**Comment by 807502278** [comment]
I'm using 17.9 without any problem. Can you try installing a few more packages from VS
![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/46019416/1aaec42b-e498-48c9-a277-7313fa510493)

**Comment by saidthebird** [comment]
Hello! thanks for the comment. Something required me so I was away for a bit. I am back. I have installed 1.17.9 like you have asked. will return after some tinkering!

**Comment by saidthebird** [comment]
resolved after updating the new 3dpack! Thanks!
