### ISSUE TITLE
ImportError: DLL load failed while importing _C: The specified procedure could not be found.

### ISSUE THREAD

**Issue by JamesLaFritz** [MrForExample/ComfyUI-3D-Pack#187]
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\ComfyUI_windows_portable\ComfyUI\main.py
** Log path: C:\ComfyUI_windows_portable\comfyui.log

Total VRAM 8188 MB, total RAM 16089 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
Using xformers cross attention
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 44, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 52, in <module>
    from .algorithms.dmtet import DMTetMesh
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\dmtet.py", line 6, in <module>
    from pytorch3d.loss import chamfer_distance, mesh_laplacian_smoothing
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pytorch3d\loss\__init__.py", line 8, in <module>
    from .chamfer import chamfer_distance
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pytorch3d\loss\chamfer.py", line 11, in <module>
    from pytorch3d.ops.knn import knn_gather, knn_points
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pytorch3d\ops\__init__.py", line 7, in <module>
    from .ball_query import ball_query
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pytorch3d\ops\ball_query.py", line 10, in <module>
    from pytorch3d import _C
ImportError: DLL load failed while importing _C: The specified procedure could not be found.

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: DLL load failed while importing _C: The specified procedure could not be found.

I have the Visual studio Installed

**Comment by JamesLaFritz** [comment]
My research shows that this dll is suppose to be in the python_embeded\Lib\site-packages\torch\lib

I have the _C.lib but the _C.dll is missing, I believe that this is not an issue with your tool but with pytorch itself

is there someplace that I can find the dll and copy it into the torch lib folder?

Directory of C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib

06/30/2024  02:21 PM    <DIR>          .
06/30/2024  02:21 PM    <DIR>          ..
06/30/2024  02:20 PM           358,912 asmjit.dll
06/30/2024  02:20 PM           125,788 asmjit.lib
06/30/2024  02:20 PM           801,792 c10.dll
06/30/2024  02:20 PM           705,272 c10.lib
06/30/2024  02:20 PM           347,648 c10_cuda.dll
06/30/2024  02:20 PM            54,290 c10_cuda.lib
06/30/2024  02:20 PM            16,384 caffe2_nvrtc.dll
06/30/2024  02:20 PM             1,850 caffe2_nvrtc.lib
06/30/2024  02:20 PM           116,450 cpuinfo.lib
06/30/2024  02:20 PM        98,058,240 cublas64_12.dll
06/30/2024  02:20 PM       538,818,048 cublasLt64_12.dll
06/30/2024  02:20 PM           527,872 cudart64_12.dll
06/30/2024  02:20 PM           288,296 cudnn64_8.dll
06/30/2024  02:20 PM       125,293,112 cudnn_adv_infer64_8.dll
06/30/2024  02:20 PM       118,691,384 cudnn_adv_train64_8.dll
06/30/2024  02:20 PM       605,947,448 cudnn_cnn_infer64_8.dll
06/30/2024  02:20 PM        97,227,320 cudnn_cnn_train64_8.dll
06/30/2024  02:20 PM        89,607,224 cudnn_ops_infer64_8.dll
06/30/2024  02:20 PM        70,172,216 cudnn_ops_train64_8.dll
06/30/2024  02:20 PM       190,346,752 cufft64_11.dll
06/30/2024  02:20 PM           295,936 cufftw64_11.dll
06/30/2024  02:20 PM         4,327,424 cupti64_2023.1.1.dll
06/30/2024  02:20 PM        63,505,408 curand64_10.dll
06/30/2024  02:20 PM       110,190,080 cusolver64_11.dll
06/30/2024  02:20 PM        77,008,384 cusolverMg64_11.dll
06/30/2024  02:20 PM       262,348,288 cusparse64_12.dll
06/30/2024  02:20 PM       635,592,728 dnnl.lib
06/30/2024  02:20 PM         4,961,280 fbgemm.dll
06/30/2024  02:20 PM         1,409,606 fbgemm.lib
06/30/2024  02:20 PM         1,668,942 fmt.lib
06/30/2024  02:20 PM        22,096,964 kineto.lib
06/30/2024  02:20 PM         1,942,464 libiomp5md.dll
06/30/2024  02:20 PM            39,872 libiompstubs5md.dll
06/30/2024  02:20 PM         5,167,484 libprotobuf-lite.lib
06/30/2024  02:20 PM        37,790,918 libprotobuf.lib
06/30/2024  02:20 PM        39,640,280 libprotoc.lib
06/30/2024  02:20 PM        34,385,920 nvJitLink_120_0.dll
06/30/2024  02:20 PM         7,001,600 nvrtc-builtins64_121.dll
06/30/2024  02:20 PM        42,161,152 nvrtc64_120_0.dll
06/30/2024  02:20 PM            48,128 nvToolsExt64_1.dll
06/30/2024  02:20 PM           189,444 pthreadpool.lib
06/30/2024  02:20 PM            14,848 shm.dll
06/30/2024  02:20 PM             3,790 shm.lib
06/30/2024  02:20 PM             9,728 torch.dll
06/30/2024  02:20 PM             1,832 torch.lib
06/30/2024  02:20 PM       130,929,152 torch_cpu.dll
06/30/2024  02:20 PM        29,408,314 torch_cpu.lib
06/30/2024  02:21 PM       876,318,208 torch_cuda.dll
06/30/2024  02:21 PM         1,957,070 torch_cuda.lib
06/30/2024  02:21 PM             9,728 torch_global_deps.dll
06/30/2024  02:21 PM        15,631,360 torch_python.dll
06/30/2024  02:21 PM           213,604 torch_python.lib
06/30/2024  02:21 PM           195,072 uv.dll
06/30/2024  02:20 PM         3,703,446 XNNPACK.lib
06/30/2024  02:21 PM            89,088 zlibwapi.dll
06/30/2024  02:20 PM             1,924 _C.lib
              56 File(s)  4,347,765,764 bytes
               2 Dir(s)  360,083,959,808 bytes free

**Comment by JamesLaFritz** [comment]
Did python.exe -s -m pip install --force-reinstall xformers==0.0.25.post1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 --extra-index-url https://pypi.org/simple

which causes 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albucore 0.0.12 requires numpy<2,>=1.24.4, but you have numpy 2.0.0 which is incompatible.
albumentations 1.4.10 requires numpy<2,>=1.24.4, but you have numpy 2.0.0 which is incompatible.
colour-science 0.4.4 requires numpy<2,>=1.22, but you have numpy 2.0.0 which is incompatible.
gradio 4.8.0 requires numpy~=1.0, but you have numpy 2.0.0 which is incompatible.
onnxruntime 1.18.1 requires numpy<2.0,>=1.21.6, but you have numpy 2.0.0 which is incompatible.
transformers 4.42.3 requires numpy<2.0,>=1.17, but you have numpy 2.0.0 which is incompatible.
ultralytics 8.2.42 requires numpy<2.0.0,>=1.23.5, but you have numpy 2.0.0 which is incompatible.

and running comfy fails because of numpy 2.0.0

so I did python.exe -s -m pip install -U transformers which installed numpy-1.26.4

and comfy now runs with this pack.

**Comment by JamesLaFritz** [comment]
I did python.exe -s -m pip install -U torch torchvision torchaudio xformers --index-url https://download.pyto
rch.org/whl/cu121 which updates to pytorch version: 2.3.0+cu121

pip install fvcore iopath
pip install "git+https://github.com/facebookresearch/pytorch3d.git"
This updates pytorch3d to version 0.7.7

Got a wired windows error popup, 
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
Using xformers cross attention
Warn!: xFormers is available (Attention)
Warn!: Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 45, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 59, in <module>
    from .algorithms.flexicubes_trainer import FlexiCubesTrainer
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\flexicubes_trainer.py", line 15, in <module>
    from ..flexicubes.loss import sdf_reg_loss
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\flexicubes\loss.py", line 9, in <module>
    import torch_scatter
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch_scatter\__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 376, in __init__
OSError: [WinError 127] The specified procedure could not be found

So I did
python.exe -s -m pip install --force-reinstall fvcore iopath 
which installs numpy 2.0.0
python.exe -s -m pip install -U transformers
to fix the numpy error

Still get the new windows pop up error.
I tried to do 
python.exe -s -m pip install --force-reinstall torch torchvision torchaudio xformers "git+https://github.com/facebookresearch/pytorch3d.git" --index-url https://download.pytorch.org/whl/cu121

but this gives me Could not find a version that satisfies the requirement fvcore (from pytorch3d) (from versions: none)

so I went ahead and did again
python_embeded>python.exe -s -m pip install --force-reinstall torch torchvision torchaudio xformers --index-url https://download
.pytorch.org/whl/cu121

realized that this was related to torch_scatter

so I did 
python.exe -s -m pip install --force-reinstall torch_scatter

I now have it working with pytorch 2.3.0+cu121, I am getting an extra warning about TORCH_CUDA_ARCH_LIST is not set but it does work now.

** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\ComfyUI_windows_portable\ComfyUI\main.py
** Log path: C:\ComfyUI_windows_portable\comfyui.log
Total VRAM 8188 MB, total RAM 16089 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
Using xformers cross attention
Warn!: xFormers is available (Attention)
Warn!: C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(

**Comment by JamesLaFritz** [comment]
Here's my final list of installed modules
C:\ComfyUI_windows_portable\python_embeded>pip list
Package                     Version
--------------------------- ------------------
absl-py                     2.1.0
accelerate                  0.31.0
addict                      2.4.0
aiofiles                    23.2.1
aiohttp                     3.9.5
aiosignal                   1.3.1
albucore                    0.0.12
albumentations              1.4.10
altair                      5.3.0
annotated-types             0.7.0
antlr4-python3-runtime      4.9.3
anyio                       4.4.0
argostranslate              1.9.6
asn1crypto                  1.5.1
atpublic                    4.1.0
attrs                       23.2.0
audioread                   3.0.1
beautifulsoup4              4.12.3
bitsandbytes                0.43.1
cachetools                  5.3.3
certifi                     2024.6.2
cffi                        1.16.0
chardet                     5.2.0
charset-normalizer          3.3.2
click                       8.1.7
cloudpickle                 2.2.1
cmake                       3.29.6
color-matcher               0.5.0
colorama                    0.4.6
coloredlogs                 15.0.1
colorlog                    6.8.2
colour-science              0.4.4
contourpy                   1.2.1
cryptography                42.0.8
cssselect2                  0.7.0
cstr                        0.1.0
ctranslate2                 4.3.1
cupy-cuda12x                13.2.0
cycler                      0.12.1
dataclasses-json            0.6.7
ddt                         1.7.2
decorator                   4.4.2
deep-translator             1.11.4
Deprecated                  1.2.14
diff-gaussian-rasterization 0.0.0
diffusers                   0.29.2
diskcache                   5.6.3
distro                      1.9.0
dnspython                   2.6.1
docutils                    0.21.2
einops                      0.7.0
email_validator             2.2.0
embreex                     2.17.7.post4
executing                   2.0.1
fairscale                   0.4.13
fastapi                     0.111.0
fastapi-cli                 0.0.4
fastrlock                   0.8.2
ffmpy                       0.3.0
filelock                    3.13.1
flatbuffers                 24.3.25
fonttools                   4.53.0
frozenlist                  1.4.1
fsspec                      2024.2.0
ftfy                        6.2.0
fvcore                      0.1.5.post20221221
gitdb                       4.0.11
GitPython                   3.1.43
glcontext                   2.5.0
googletrans-py              4.0.0
gradio                      4.8.0
gradio_client               0.7.1
h11                         0.14.0
h2                          4.1.0
hpack                       4.0.0
httpcore                    1.0.5
httptools                   0.6.1
httpx                       0.27.0
huggingface-hub             0.23.4
humanfriendly               10.0
hyperframe                  6.0.1
idna                        3.7
imageio                     2.34.2
imageio-ffmpeg              0.5.1
img2texture                 1.1.2.post2
importlib_metadata          8.0.0
importlib_resources         6.4.0
intel-openmp                2021.4.0
iopath                      0.1.10
jax                         0.4.30
jaxlib                      0.4.30
jaxtyping                   0.2.31
Jinja2                      3.1.3
joblib                      1.4.2
jsonschema                  4.22.0
jsonschema-specifications   2023.12.1
kiui                        0.2.4
kiwisolver                  1.4.5
kornia                      0.7.2
kornia_rs                   0.1.3
lazy_loader                 0.4
librosa                     0.10.2.post1
lightning-utilities         0.11.3.post0
llama_cpp_python            0.2.26+cu121
llvmlite                    0.43.0
lxml                        5.2.2
mapbox-earcut               1.0.1
markdown-it-py              3.0.0
MarkupSafe                  2.1.5
marshmallow                 3.21.3
matplotlib                  3.9.0
matrix-client               0.4.0
mdurl                       0.1.2
mediapipe                   0.10.14
mkl                         2021.4.0
ml-dtypes                   0.4.0
moderngl                    5.10.0
moviepy                     1.0.3
mpmath                      1.3.0
msgpack                     1.0.8
msvc_runtime                14.40.33807
multidict                   6.0.5
mypy-extensions             1.0.0
nerfacc                     0.5.3
networkx                    3.2.1
ninja                       1.11.1.1
numba                       0.60.0
numpy                       1.26.3
nvdiffrast                  0.3.1
objprint                    0.2.3
omegaconf                   2.3.0
onnxruntime                 1.18.1
open-clip-torch             2.24.0
opencv-contrib-python       4.10.0.84
opencv-python               4.10.0.84
opencv-python-headless      4.10.0.84
opt-einsum                  3.3.0
orjson                      3.10.5
packaging                   24.1
pandas                      2.2.2
piexif                      1.1.3
pilgram                     1.2.1
pillow                      10.2.0
pip                         24.1.1
pixeloe                     0.0.10
platformdirs                4.2.2
plyfile                     1.0.3
pointnet2-ops               3.0.0
pooch                       1.8.2
portalocker                 2.10.0
proglog                     0.1.10
protobuf                    4.25.3
psutil                      5.9.8
py-cpuinfo                  9.0.0
pycollada                   0.8
pycparser                   2.22
pydantic                    2.7.4
pydantic_core               2.18.4
pydub                       0.25.1
pygit2                      1.15.0
PyGithub                    2.3.0
pygltflib                   1.16.2
Pygments                    2.18.0
pyhocon                     0.3.61
PyJWT                       2.8.0
PyMatting                   1.1.12
PyMCubes                    0.1.4
pymeshlab                   2023.12.post1
PyNaCl                      1.5.0
pyOpenSSL                   24.1.0
pyparsing                   3.1.2
pyreadline3                 3.4.1
python-dateutil             2.9.0.post0
python-dotenv               1.0.1
python-multipart            0.0.9
pytorch-lightning           2.3.1
pytorch-msssim              1.0.0
pytorch3d                   0.7.7
pytz                        2024.1
pywin32                     306
PyYAML                      6.0.1
referencing                 0.35.1
regex                       2024.5.15
rembg                       2.0.57
reportlab                   4.2.2
requests                    2.32.3
rich                        13.7.1
roma                        1.5.0
rpds-py                     0.18.1
Rtree                       1.2.0
sacremoses                  0.0.53
safetensors                 0.4.3
scikit-build                0.18.0
scikit-image                0.24.0
scikit-learn                1.5.0
scipy                       1.13.1
seaborn                     0.13.2
segment-anything            1.0
semantic-version            2.10.0
sentencepiece               0.2.0
setuptools                  70.2.0
shapely                     2.0.4
shellingham                 1.5.4
simple-knn                  0.0.0
six                         1.16.0
smmap                       5.0.1
sniffio                     1.3.1
snowflake                   0.10.0
snowflake-connector-python  3.11.0
snowflake.core              0.10.0
snowflake._legacy           0.10.0
snowflake-snowpark-python   1.19.0
sortedcontainers            2.4.0
sounddevice                 0.4.7
soundfile                   0.12.1
soupsieve                   2.5
soxr                        0.3.7
spandrel                    0.3.4
stanza                      1.1.1
starlette                   0.37.2
svg.path                    6.3
svglib                      1.5.1
sympy                       1.12
tabulate                    0.9.0
tbb                         2021.11.0
termcolor                   2.4.0
threadpoolctl               3.5.0
tifffile                    2024.6.18
timm                        1.0.7
tinycss2                    1.3.0
tokenizers                  0.19.1
tomli                       2.0.1
tomlkit                     0.12.0
toolz                       0.12.1
torch                       2.3.0+cu121
torch_scatter               2.1.2
torchaudio                  2.3.0+cu121
torchmcubes                 0.1.0
torchmetrics                1.4.0.post0
torchsde                    0.2.6
torchtyping                 0.1.4
torchvision                 0.18.0+cu121
tqdm                        4.66.4
trampoline                  0.1.2
transformers                4.42.3
trimesh                     4.0.5
triton-library              1.0.0rc4
typeguard                   2.13.3
typer                       0.12.3
typing_extensions           4.9.0
typing-inspect              0.9.0
tzdata                      2024.1
ujson                       5.10.0
ultralytics                 8.2.42
ultralytics-thop            2.0.0
urllib3                     1.26.19
uvicorn                     0.30.1
varname                     0.13.1
vhacdx                      0.0.8.post0
watchfiles                  0.22.0
wcwidth                     0.2.13
webencodings                0.5.1
websockets                  11.0.3
wheel                       0.43.0
wrapt                       1.16.0
xatlas                      0.0.9
xformers                    0.0.26.post1
xxhash                      3.4.1
yacs                        0.1.8
yapf                        0.40.2
yarl                        1.9.4
zipp                        3.19.2

**Comment by JamesLaFritz** [comment]
# Just did this on my desktop as well.
Followed the install directions for method 0, using python-embedded batch file.
.\python_embeded\python.exe\python.exe -s -m pip install --force-reinstall xformers==0.0.25.post1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 --extra-index-url https://pypi.org/simple
.\python_embeded\python.exe -s -m pip install -U transformers fixes numpy
.\python_embeded\python.exe -s -m pip install -U torch torchvision torchaudio xformers --index-url https://download.pyto
rch.org/whl/cu121 which updates to pytorch version: 2.3.0+cu121
.\python_embeded\python.exe -s -m pip install fvcore iopath
.\python_embeded\python.exe -s -m pip install "git+https://github.com/facebookresearch/pytorch3d.git" updates pytorch3d
.\python_embeded\python.exe  -s -m pip install --force-reinstall torch_scatter

## For some reason there where some modules missing. For ComfyUI-3D-Pack
- [2024-07-08 23:14] Cannot import E:\Tools\Stable-Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'roma'

.\python_embeded\python.exe  -s -m pip install roma 

- OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root. 
- [2024-07-08 23:21] Warn!: Cannot import E:\Tools\Stable-Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

Download and instaled the [Cuda Toolkit](https://developer.nvidia.com/cuda-toolkit) I used 12.5. Update 1 for windows. I already had this installed on my laptop.

- I probably could have done
.\python_embeded\python.exe -m pip install --upgrade setuptools pip wheel
.\python_embeded\python.exe -m pip install nvidia-pyindex
.\python_embeded\python.exe -m pip install nvidia-cuda-runtime-cu12
.\python_embeded\python.exe -m pip install  nvidia-<library>what ever library that is needed but installing the toolkit is just easier.

```
## ComfyUI-Manager: installing dependencies done.
[2024-07-09 00:14] ** ComfyUI startup time: 2024-07-09 00:14:52.352468
[2024-07-09 00:14] ** Platform: Windows
[2024-07-09 00:14] ** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
[2024-07-09 00:14] ** Python executable: E:\Tools\Stable-Diffusion\ComfyUI_windows_portable\python_embeded\python.exe
[2024-07-09 00:14] ** Log path: E:\Tools\Stable-Diffusion\ComfyUI_windows_portable\comfyui.log
Total VRAM 8192 MB, total RAM 49088 MB
[2024-07-09 00:15] pytorch version: 2.3.0+cu121
[2024-07-09 00:15] xformers version: 0.0.26.post1
[2024-07-09 00:15] Set vram state to: NORMAL_VRAM
[2024-07-09 00:15] Device: cuda:0 NVIDIA GeForce GTX 1070 : cudaMallocAsync
[2024-07-09 00:15] Using xformers cross attention
[2024-07-09 00:17]   66.1 seconds: E:\Tools\Stable-Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack
```

**Comment by WorkSync** [comment]
> # Just did this on my desktop as well.
> 刚刚在我的桌面上也这样做了。
> Followed the install directions for method 0, using python-embedded batch file.按照方法 0 的安装说明，使用 python-embedded 批处理文件。 .\python_embeded\python.exe\python.exe -s -m pip install --force-reinstall xformers==0.0.25.post1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 --extra-index-url https://pypi.org/simple .\python_embeded\python.exe -s -m pip install -U transformers fixes numpy.\python_embeded\python.exe -s -m pip install -U transformers 修复 numpy .\python_embeded\python.exe -s -m pip install -U torch torchvision torchaudio xformers --index-url https://download.pyto rch.org/whl/cu121 which updates to pytorch version: 2.3.0+cu121rch.org/whl/cu121 更新到 pytorch 版本：2.3.0+cu121 .\python_embeded\python.exe -s -m pip install fvcore iopath .\python_embeded\python.exe -s -m pip install "git+https://github.com/facebookresearch/pytorch3d.git" updates pytorch3d.\python_embeded\python.exe -s -m pip install “git+ https://github.com/facebookresearch/pytorch3d.git” updates pytorch3d .\python_embeded\python.exe -s -m pip install --force-reinstall torch_scatter
> 
> ## For some reason there where some modules missing. For ComfyUI-3D-Pack
> 由于某种原因，缺少一些模块。适用于 ComfyUI-3D-Pack
> * [2024-07-08 23:14] Cannot import E:\Tools\Stable-Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'roma'[2024-07-08 23:14]无法导入自定义节点的 E：\Tools\Stable-Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack 模块：没有名为“roma”的模块
> 
> .\python_embeded\python.exe -s -m pip install roma
> 
> * OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.OSError：未设置CUDA_HOME环境变量。请将其设置为您的 CUDA 安装根目录。
> * [2024-07-08 23:21] Warn!: Cannot import E:\Tools\Stable-Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.[2024-07-08 23:21]警告：无法导入自定义节点的 E：\Tools\Stable-Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack 模块：CUDA_HOME未设置环境变量。请将其设置为您的 CUDA 安装根目录。
> 
> Download and instaled the [Cuda Toolkit](https://developer.nvidia.com/cuda-toolkit) I used 12.5. Update 1 for windows. I already had this installed on my laptop.下载并安装了我使用的 Cuda Toolkit 12.5。适用于 Windows 的 Update 1。我已经在我的笔记本电脑上安装了它。
> 
> * I probably could have done我本来可以做到的
>   .\python_embeded\python.exe -m pip install --upgrade setuptools pip wheel
>   .\python_embeded\python.exe -m pip install nvidia-pyindex
>   .\python_embeded\python.exe -m pip install nvidia-cuda-runtime-cu12.\python_embeded\python.exe -m pip 安装 nvidia-cuda-runtime-cu12
>   .\python_embeded\python.exe -m pip install  nvidia-what ever library that is needed but installing the toolkit is just easier..\python_embeded\python.exe -m pip install nvidia-any library that is needed 但安装工具包更容易。
> 
> ```
> ## ComfyUI-Manager: installing dependencies done.
> [2024-07-09 00:14] ** ComfyUI startup time: 2024-07-09 00:14:52.352468
> [2024-07-09 00:14] ** Platform: Windows
> [2024-07-09 00:14] ** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
> [2024-07-09 00:14] ** Python executable: E:\Tools\Stable-Diffusion\ComfyUI_windows_portable\python_embeded\python.exe
> [2024-07-09 00:14] ** Log path: E:\Tools\Stable-Diffusion\ComfyUI_windows_portable\comfyui.log
> Total VRAM 8192 MB, total RAM 49088 MB
> [2024-07-09 00:15] pytorch version: 2.3.0+cu121
> [2024-07-09 00:15] xformers version: 0.0.26.post1
> [2024-07-09 00:15] Set vram state to: NORMAL_VRAM
> [2024-07-09 00:15] Device: cuda:0 NVIDIA GeForce GTX 1070 : cudaMallocAsync
> [2024-07-09 00:15] Using xformers cross attention
> [2024-07-09 00:17]   66.1 seconds: E:\Tools\Stable-Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack
> ```

Did you solve it ? I met same problems.

**Comment by JamesLaFritz** [comment]
Yes. I did. Both on my laptop and my desktop.
