### ISSUE TITLE
Framework Integration

### ISSUE THREAD

**Issue by vararth** [MrForExample/ComfyUI-3D-Pack#2]
NOT AN ISSUE

Just wondering - do you think it is possible to integrate something like [threestudio](https://github.com/threestudio-project/threestudio) or [dreamgaussian](https://github.com/dreamgaussian/dreamgaussian) with ComfyUI?

**Comment by MrForExample** [comment]
Of course my friend, actually part of my code for bake the texture on the the 3D mesh is improved from dreamgaussian

But regards threestudio, most of algorithm inside of it took forever to run even on a above average PC, according to the original design philosophy of ComfyUI, my plan for now is only bring the best algorithm with acceptable runtime cost into this project.

Please keep in mind this is project is still a working progress, so far there is only one algorithm which bake the rendered multi-view images into the UV texture of a 3D mesh, and I only manage to make it work inside Miniconda/Conda environment with cuda 11.8 and corresponding torch version.

Thanks for your attention to this project, to be frankly I didn't expect this half working thing to get any attention this soon, but I'll do my best to bring the this 3D AI Tools for everyone :)

**Comment by vararth** [comment]
Thanks @MrForExample - I have actually set up both threestusio and dreamgaussian and been trying to explore how to create API calls between environments for use with comfyui since the base image required for 3D generation is superior if controlled with workflows instead of simple prompts -

Would love to collaborate on this with you but tbh I have no clue where to start!

**Comment by MrForExample** [comment]
> the base image required for 3D generation is superior if controlled with workflows instead of simple prompts

**You speak my mind :)**

Since the main benefit of using UI workflows is modularity, so my plan is to get the core modules done first, i.e. the most commonly used algorithms (e.g. 3DGS, Nerf, DMTet, differentiable rendering, and those SDS/VSD optimization etc.) and linkage nodes like load & save common 3D file (e.g. obj, fbx, ply, glb) and some common mesh processor.

If you want collaborate that's great! you can start by look into Nerf or [kaolin](https://github.com/NVIDIAGameWorks/kaolin) and other ComfyUI addons, my plan for the rest of the day is to bring a improved version of 3DGS into the project.

Feel free to DM me on twitter or reddit if you have any questions that you think I may know the answer :)
Cheers 👍

**Comment by v4r4rth** [comment]
Hey - can you please confirm if the workflows enable just 3d-to-3d or also text-to-3d?
Also, I have figured out a very basic and simple workflow to enable high resolution stablezero123 generations, if you like you can check out the attached image, file work
![ComfyUI_temp_zbiae_00064_](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/149033251/ba6b447c-c6f9-496a-947b-758b382dbd8d)
flow embedded :)

**Comment by MrForExample** [comment]
> Hey - can you please confirm if the workflows enable just 3d-to-3d or also text-to-3d? Also, I have figured out a very basic and simple workflow to enable high resolution stablezero123 generations, if you like you can check out the attached image, file work ![ComfyUI_temp_zbiae_00064_](https://private-user-images.githubusercontent.com/149033251/297271678-ba6b447c-c6f9-496a-947b-758b382dbd8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTI4MzQsIm5iZiI6MTcwNjE5MjUzNCwicGF0aCI6Ii8xNDkwMzMyNTEvMjk3MjcxNjc4LWJhNmI0NDdjLWM2ZjktNDk2YS05NDdiLTc1OGIzODJkYmQ4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQxNDIyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTFmN2IyMzM5Yjk0MTgwZDBkNzRiMjk3NzMxZWUyZGQ1ZTIzMWRjY2U2NTJkMzE3YWU0MjlhODVjOWM1ODMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.99qWwftgnWXLQrncy461iHvn7Ww4-Pzts5zNz8qC15E) flow embedded :)

Nice work friend.
I just updated the package, now the example workflow [Triplane_Gaussian_Transformers_to_3DGS.json](https://github.com/MrForExample/ComfyUI-3D-Pack/blob/main/_Example_Workflows/Triplane_Gaussian_Transformers_to_3DGS.json) supports single image to 3DGS, and you can later use DMTet node to convert it into 3D Mesh, however to bake the render of the 3DGS onto the texture, currently you have to generate the rendered images first then use Bake Multi-View images into UVTexture node. I will make it simpler in the near future.
Cheers 👍

**Comment by v4r4rth** [comment]
So I finally got around to setting up the 3D-Pack and wow! I am so happy I was patient!
Gaussian Splatting is working phenomenolly, but I did face an issue with the suggested Cammy workflow - the mesh was not nearly as good as what you have shown in the Readme -

![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/149033251/1a42c912-2bbe-40f6-8281-738240fc8a3d)


Please suggest what parameters I could play around with for getting the same quality! I am using the default suggested workflow for this :)

**Comment by v4r4rth** [comment]
Additional Request:
You have shared nodes to save 3DGS and 3D Mesh, could you also please provide a node to save the Point Cloud? Asking so I can check how the 3DGS to Point Cloud node works prior to the 3D Mesh Generation :)

**Comment by xabila** [comment]
I have exactly the same problem with the mesh generation... 
by the way i did try  3 version of Cuda before making it work , we need to use this one : https://developer.nvidia.com/cuda-12-1-0-download-archive

**Comment by MrForExample** [comment]
Hi, friends, you guys can try the newest 3DGS to Mesh Conversion Algorithm node: `Convert_3DGS_to_Mesh_with_NeRF_and_Marching_Cubes`
It works much better

**Comment by xabila** [comment]
Perfect thanks

Le ven. 9 févr. 2024 à 11:56, Mr. For Example ***@***.***> a
écrit :

**Comment by einstein33** [comment]
> Hi, friends, you guys can try the newest 3DGS to Mesh Conversion Algorithm node: `Convert_3DGS_to_Mesh_with_NeRF_and_Marching_Cubes` It works much better

Can you explain in detail how to handle this?
