### ISSUE TITLE
Nodes missing when attempting to use example workflows, and no mention made in install instructions

### ISSUE THREAD

**Issue by Duodecimus** [MrForExample/ComfyUI-3D-Pack#200]
Installed comfyUI
Installed comfyUIManager
Installed Comfy3dpack via manager

I then get this error (among others) when opening the example workflows
![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/5687003/7501df5a-85f0-4844-890e-f8eb4bf9c29b)

for searching, the missing nodes are:
INTConstant
IPAdapterAdvanced
IPAdapterModelLoader
PrepImageForClipVision
VHS_MergeImages
GetImagesFromBatchIndexed
ImpactFloat
UltimateSDUpscale
LoadImagesFromDir //Inspire
IMG_padder
Image Rembg (Remove Background)

these nodes are from
 https://github.com/cubiq/ComfyUI_IPAdapter_plus
 https://github.com/kijai/ComfyUI-KJNodes
 https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
 https://github.com/ltdrdata/ComfyUI-Impact-Pack
 https://github.com/ssitu/ComfyUI_UltimateSDUpscale
 https://github.com/ltdrdata/ComfyUI-Inspire-Pack
 https://github.com/edenartlab/eden_comfy_pipelines
 https://github.com/WASasquatch/was-node-suite-comfyui

some mention should be made of this list in the install section of the readme

**Comment by MrForExample** [comment]
Hi @Duodecimus thanks for written a list of all the ComfyUI addons that is used in my example workflows 
I did mention: **If you have any missing node in any open Comfy3D workflow, try simply click [Install Missing Custom Nodes](https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#support-of-missing-nodes-installation) in ComfyUI-Manager** in [README file](https://github.com/MrForExample/ComfyUI-3D-Pack?tab=readme-ov-file#install)

Cheers, have a good day 👍
