### ISSUE TITLE
cuda version error and cstr error

### ISSUE THREAD

**Issue by daehwa00** [MrForExample/ComfyUI-3D-Pack#201]
## ComfyUI-Manager: EXECUTE => ['/home/daehwa/miniconda3/envs/ComfyUI/bin/python', 'install.py']
[!] Traceback (most recent call last):
[!]   File "/home/daehwa/Documents/ComfyUI/custom_nodes/ComfyUI-3D-Pack/install.py", line 19, in <module>
[!]     from build_utils import (
[!]   File "/home/daehwa/Documents/ComfyUI/custom_nodes/ComfyUI-3D-Pack/_Pre_Builds/_Build_Scripts/build_utils.py", line 41, in <module>
[!]     CUDA_VERSION = get_cuda_version()
[!]                    ^^^^^^^^^^^^^^^^^^
[!]   File "/home/daehwa/Documents/ComfyUI/custom_nodes/ComfyUI-3D-Pack/_Pre_Builds/_Build_Scripts/build_utils.py", line 38, in get_cuda_version
[!]     raise RuntimeError(f"Please install/reinstall CUDA tookit with any of the following supported version: {build_config.supported_cuda_versions}")
[!] RuntimeError: Please install/reinstall CUDA tookit with any of the following supported version: ['12.1', '11.8']
[!] 
[!] During handling of the above exception, another exception occurred:
[!] 
[!] Traceback (most recent call last):
[!]   File "/home/daehwa/Documents/ComfyUI/custom_nodes/ComfyUI-3D-Pack/install.py", line 83, in <module>
[!]     cstr("Comfy3D install failed: Dependency installation has failed. Please install manually: https://github.com/MrForExample/ComfyUI-3D-Pack/tree/main/_Pre_Builds/README.md.").error.print()
[!]     ^^^^
[!] NameError: name 'cstr' is not defined. Did you mean: 'str'?
install script failed: https://github.com/MrForExample/ComfyUI-3D-Pack
Attempt to fixing '['https://github.com/MrForExample/ComfyUI-3D-Pack']' is done.
After restarting ComfyUI, please refresh the browser.

I got the above error.

but when the print the my computer's Cuda driver version, It correctly worked.
What is the matter? Thank you.

daehwa@daehwa:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

**Comment by MrForExample** [comment]
Hi @daehwa00 I'm not sure exactly why that's the case for you, if that's your nvcc output then it should pick it up.

But we can do a simple debug first, can you go to _Pre_Builds\_Build_Scripts\build_utils.py at line 33 add following and see what's been print out: 
print(f"[DEBUG] Returncode: {result.returncode} \n Output: {result.stdout} \n Error: {result.stderr}")

**Comment by MrForExample** [comment]
Just updated the build script, that issue is fixed now! Cheers

**Comment by daehwa00** [comment]
Thank you for your help 😀
