### ISSUE TITLE
Import Failed bug

### ISSUE THREAD

**Issue by al3dv2** [MrForExample/ComfyUI-3D-Pack#21]
Hi I have follow all the instruction but I have import failed bug I'm using windows 10 and 24go vram nvidia card 
![arfff](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/157552424/a39ea882-4d02-4795-859e-e37ee753c76e)

**Comment by MrForExample** [comment]
Please stroll up your comfyUI console, it should tell you which package caused the import failure, also make sure to use the correct `run_nvidia_gpu_miniconda.bat` to [start the comfyUI](https://github.com/MrForExample/ComfyUI-3D-Pack?tab=readme-ov-file#run)

**Comment by al3dv2** [comment]
Thanks for the answer but I tried every stuff written on the main page but the import doesn't work here the full console : 

C:\ComfyUI_windows_portable>.\python_miniconda_env\ComfyUI\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-02-09 12:32:16.252251
** Platform: Windows
** Python version: 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
** Python executable: C:\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\python.exe
** Log path: C:\ComfyUI_windows_portable\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

Install: pip packages for 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\StableZero123-comfyui'
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
 Requirement already satisfied: diffusers~=0.21.4 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (0.21.4)
 Requirement already satisfied: Pillow in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from diffusers~=0.21.4) (9.5.0)
 Requirement already satisfied: filelock in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from diffusers~=0.21.4) (3.9.0)
 Requirement already satisfied: huggingface-hub>=0.13.2 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from diffusers~=0.21.4) (0.20.3)
 Requirement already satisfied: importlib-metadata in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from diffusers~=0.21.4) (7.0.1)
 Requirement already satisfied: numpy in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from diffusers~=0.21.4) (1.26.3)
 Requirement already satisfied: regex!=2019.12.17 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from diffusers~=0.21.4) (2023.12.25)
 Requirement already satisfied: requests in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from diffusers~=0.21.4) (2.28.1)
 Requirement already satisfied: safetensors>=0.3.1 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from diffusers~=0.21.4) (0.4.2)
 Requirement already satisfied: fsspec>=2023.5.0 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from huggingface-hub>=0.13.2->diffusers~=0.21.4) (2024.2.0)
 Requirement already satisfied: tqdm>=4.42.1 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from huggingface-hub>=0.13.2->diffusers~=0.21.4) (4.66.1)
 Requirement already satisfied: pyyaml>=5.1 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from huggingface-hub>=0.13.2->diffusers~=0.21.4) (6.0.1)
 Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from huggingface-hub>=0.13.2->diffusers~=0.21.4) (4.8.0)
 Requirement already satisfied: packaging>=20.9 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from huggingface-hub>=0.13.2->diffusers~=0.21.4) (23.2)
 Requirement already satisfied: zipp>=0.5 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from importlib-metadata->diffusers~=0.21.4) (3.17.0)
 Requirement already satisfied: charset-normalizer<3,>=2 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from requests->diffusers~=0.21.4) (2.1.1)
 Requirement already satisfied: idna<4,>=2.5 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from requests->diffusers~=0.21.4) (3.4)
 Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from requests->diffusers~=0.21.4) (1.26.13)
 Requirement already satisfied: certifi>=2017.4.17 in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from requests->diffusers~=0.21.4) (2022.12.7)
 Requirement already satisfied: colorama in c:\comfyui_windows_portable\python_miniconda_env\comfyui\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.13.2->diffusers~=0.21.4) (0.4.6)

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   7.6 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 41964 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 Quadro RTX 6000 : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
torch version---------------------- 2.2.0+cu121
torch version---------------------- 2.2.0+cu121
C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\lgm\core\attention.py:28: UserWarning: xFormers is not available (Attention)
  warnings.warn("xFormers is not available (Attention)")
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 18, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 37, in <module>
    from .lgm.mvdream.pipeline_mvdream import MVDreamPipeline
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\lgm\mvdream\pipeline_mvdream.py", line 18, in <module>
    from lgm.mvdream.mv_unet import MultiViewUNetModel, get_camera
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\lgm\mvdream\mv_unet.py", line 15, in <module>
    import xformers
ModuleNotFoundError: No module named 'xformers'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'xformers'
### Loading: ComfyUI-Impact-Pack (V4.74)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\__init__.py", line 1, in <module>
    from .InstantIDNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 14, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID module for custom nodes: No module named 'insightface'
### Loading: ComfyUI-Manager (V2.5.1)
### ComfyUI Revision: 1943 [eeca7248] | Released on '2024-01-31'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
--------------
 ### Mixlab Nodes: Loaded
## lama torchscript model not found: C:\ComfyUI_windows_portable\ComfyUI\models\lama/big-lama.pt,pls download from https://github.com/enesmsahin/simple-lama-inpainting/releases/download/v0.1.0/big-lama.pt
LaMaInpainting.available True
## clip_interrogator_model not found: C:\ComfyUI_windows_portable\ComfyUI\models\clip_interrogator/Salesforce/blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: C:\ComfyUI_windows_portable\ComfyUI\models\prompt_generator/text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: C:\ComfyUI_windows_portable\ComfyUI\models\prompt_generator/opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
 --------------
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Panda3d\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Panda3d\nodes.py", line 1, in <module>
    from panda3d.core import loadPrcFileData
ModuleNotFoundError: No module named 'panda3d'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Panda3d module for custom nodes: No module named 'panda3d'
3D OpenPose Editor: Loaded
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py", line 57, in <module>
    from .ScheduledNodes import (
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 4, in <module>
    import numexpr
ModuleNotFoundError: No module named 'numexpr'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: No module named 'numexpr'
[comfy_mtb] | INFO -> loaded 55 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (10) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Total VRAM 24576 MB, total RAM 41964 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 Quadro RTX 6000 : cudaMallocAsync
VAE dtype: torch.float32
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\__init__.py", line 8, in <module>
    from custom_nodes.facerestore_cf.facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\__init__.py", line 14, in <module>
    from custom_nodes.facerestore_cf.basicsr.utils.registry import ARCH_REGISTRY
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\basicsr\__init__.py", line 5, in <module>
    from .losses import *
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\basicsr\losses\__init__.py", line 5, in <module>    from .losses import (CharbonnierLoss, GANLoss, L1Loss, MSELoss, PerceptualLoss, WeightedTVLoss, g_path_regularize,
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\basicsr\losses\losses.py", line 2, in <module>
    import lpips
ModuleNotFoundError: No module named 'lpips'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf module for custom nodes: No module named 'lpips'
[WAS Extras] Loading extra custom nodes...
[WAS Extras]  Import times for extras:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\ConditioningBlend.py
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\DebugThis.py
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\VAEEncodeForInpaint.py
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\VividSharpen.py
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\ksampler_sequence.py
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\BLVaeEncode.py

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\tri3d-comfyui-nodes
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\StableZero123-comfyui
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Panda3d
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-StableSR
   0.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.1 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.7 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.8 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\AInseven
   0.9 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   2.6 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   3.7 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack

https_key OK:  C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\certificate.crt C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\private.key
Starting server

**Comment by al3dv2** [comment]
I really want to install your project that look awesome and try this workflow with https://github.com/MrForExample/ComfyUI-3D-Pack/issues/20

**Comment by MrForExample** [comment]
Seems you are missing `xformers` package, you can just run: `pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121` in miniconda env
Usually other diffusion model users have this installed already, I think that's why this issue just being bought up, I'll update the install script, thanks for testing, cheers :)

**Comment by al3dv2** [comment]
It's works now thank you !!
