### ISSUE TITLE
'Charactergen MVDiffusion Model' node fails to parse images generated in workflow

### ISSUE THREAD

**Issue by Duodecimus** [MrForExample/ComfyUI-3D-Pack#224]
When I generate an image, say with SD, and then pass it to the node it fails to produce anything legible.
![image](https://github.com/user-attachments/assets/a6939470-36f8-4392-b7b5-4f567e676f0c)

But if I save that same image and load it it, it works fine.
![image](https://github.com/user-attachments/assets/36eac487-2337-480e-9072-3386a05f563d)

Is there a cleaning step of some sort that needs to be taken for this to work?
[example broken workflow.json](https://github.com/user-attachments/files/16290146/example.broken.workflow.json)

**Comment by MrForExample** [comment]
@Duodecimus Hi
There are a few settings I corrected for you, most important one is `reference_image `need to be RGB not RGBA
[example.worked.workflow.json](https://github.com/user-attachments/files/16326328/example.worked.workflow.json)
Cheers 👍

**Comment by Duodecimus** [comment]
That worked perfectly, thank you
