### ISSUE TITLE
Is impossible to install this extension in comfyui!!

### ISSUE THREAD

**Issue by merecesarchviz** [MrForExample/ComfyUI-3D-Pack#23]
Im trying to install the pack but always i got the same problems! i began to try in my comfyui portable version not work!  i go ahead to a comfyui install envriroment in windows and I´m also getting the same problems!

first problem is in the step of the diff-gaussian-rasterization install i got always errors: 

![errorsss](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/79140456/371fe35f-7bb5-4a9c-8779-3c12dca03ae5)

any help how can solve this and can install the pack?

**Comment by MrForExample** [comment]
Hi friend.
As I mentioned in the install instruction, you can:
1. install using [Miniconda](https://docs.conda.io/projects/miniconda/en/latest/)/conda
2. install using [chocolatey](https://chocolatey.org/)

If you don't want either then you have to set up VS build tools yourself, cheers, have a good weekend :)

**Comment by DeepSkyObjects** [comment]
Try to install the proper Pytorch instead of the automatic version
# CUDA 11.8
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118
# CUDA 12.1
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121

**Comment by merecesarchviz** [comment]
df

> Try to install the proper Pytorch instead of the automatic version
> # CUDA 11.8
> 
> pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118
> # CUDA 12.1
> 
> pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121

I tried but still not work, something are not ok with the requiriments! btu the strange is i got same errors installing it in the portable version or the full with windows enviroment!

**Comment by Mikerhinos** [comment]
I'm having the exact same error, torch is installed properly, I'm not using a portable version of ComfyUI but a standard install.
