### ISSUE TITLE
Error with Bake Texture To Mesh

### ISSUE THREAD

**Issue by al3dv2** [MrForExample/ComfyUI-3D-Pack#24]
I have a error wit bake texture to mesh : 
![error1](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/157552424/c5ca00b7-4739-493e-8cd4-894fb5e8046c)
![error2](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/157552424/2e69ef41-3033-4da6-bb53-ce0ba23f6001)

**Comment by al3dv2** [comment]
I have this error in the console : C:\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\Lib\site-packages\torch\include\ATen/cuda/CUDAContextLight.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : 'cuda_runtime_api.h' : No such file or directory
ninja: build stopped: subcommand failed.

**Comment by al3dv2** [comment]
I found the solution my path of CUDA_HOME was not the right in environment variable

**Comment by WorkSync** [comment]
> I found the solution my path of CUDA_HOME was not the right in environment variable

Could you please tell me how to set CUDA_HOME?
