### ISSUE TITLE
model location

### ISSUE THREAD

**Issue by JasonSongPeng** [MrForExample/ComfyUI-3D-Pack#25]
Thanks for your amazing work！
Can you explain in detail how to place the corresponding model?
![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/57006745/9b184803-1fc4-403e-b995-fcb031bcb491)

**Comment by al3dv2** [comment]
You need to create a "chekpoints" folder then a "lgm" folder in "ComfyUI-3D-Pack" and put the model file that seems to be : https://huggingface.co/ashawkey/LGM/tree/main

**Comment by MrForExample** [comment]
Different models will be placed under `checkpoints/[model name]`:
For example:
- checkpoints/lgm
- checkpoint/tgs


Still, this is a small inconvenient for running model for the first time, ok, I'll fix this issue in the next update so it will automatically download the model if you don't have it
