### ISSUE TITLE
Excuse me, can adapt to the new UI?

### ISSUE THREAD

**Issue by 807502278** [MrForExample/ComfyUI-3D-Pack#288]
When switching to the new UI, there is an interface below that blocks a lot of things
![image](https://github.com/user-attachments/assets/765c5fc1-4275-4c2e-b168-c265cdf1672c)

**Comment by 807502278** [comment]
Even if you switch to the old UI, the preview node will always show loading and cannot work.
![image](https://github.com/user-attachments/assets/c33bf576-784e-465c-87cc-be6bb4705972)

**Comment by jakechai** [comment]
Fixed here:
https://github.com/MrForExample/ComfyUI-3D-Pack/issues/291

**Comment by MrForExample** [comment]
3D preview nodes now support new ComfyUI's Frontend

**Comment by 807502278** [comment]
Thank you very much for fixing the preview. 
When I use the preview for ply, it still seems unusable (only obj can be previewed).
Moreover, there are still some problems when switching to the new - version UI.
![image](https://github.com/user-attachments/assets/1251b3fd-fb84-4288-80a4-45340b90a172)
