### ISSUE TITLE
3d mesh is not showing:   importmap seems not working.  Import "three" failed

### ISSUE THREAD

**Issue by cloudyian** [MrForExample/ComfyUI-3D-Pack#291]
3d Mesh is not showing:    loading scene...         

  error loading extension /extensions/ComfyUI-3D-Pack/js/threeVisualizer.js TypeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./", or "../".

![Screenshot 2024-08-31 214325](https://github.com/user-attachments/assets/4d8ce1ed-0e3c-4627-b648-4d3f5a1a23fb)
![image](https://github.com/user-attachments/assets/71419824-ba7c-4467-b215-cd0e6ba61e69)

**Comment by omeganow** [comment]
Had the same issue. Seems to be related to the frontend change of ComfyUI and how the .js extensions are loaded I guess they are loaded before the html with the importmap statement. 

Falling back to the legacy frontend seems to work for me `--front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest` ([ComfyUI/pull/4379](https://github.com/comfyanonymous/ComfyUI/pull/4379))

**Comment by MrForExample** [comment]
3D preview nodes now support new ComfyUI's Frontend, cheers 👍

**Comment by 807502278** [comment]
I added this when starting the bat. 
--front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest
But preview 3dgs still cannot be used in the latest version, Only preview mesh can be used
![image](https://github.com/user-attachments/assets/1e5d4245-6b07-4c23-8efe-b2121d2d6de6)

**Comment by MrForExample** [comment]
Hi @807502278 
There is a small bug in 3DGS preview, I fixed already, and it will be available in next update, cheers, have a good weekend 👍

**Comment by 807502278** [comment]
@MrForExample  it can be previewed now and there are no bugs. It's very useful. Thank you very much.
Well, I may have to work overtime on weekends to do the work about inverse camera pose. I have already done half of it, but I feel that I may not be able to finish it...

**Comment by Erwin11** [comment]
I'm running the old version of comfyui (2024-07-22), it shows this bug.  Not with New TS UI  in comfyui.
Finally I found this is works. just close it that calls "Chrome Setting: Use graphics acceleration when available "
![closeGPU](https://github.com/user-attachments/assets/87719b6a-9dc7-42e2-a6bb-61342bc7bff0)

**Comment by 15713630716** [comment]
> 3d 网格未显示：正在加载场景...
> 
> 加载扩展时出错 /extensions/ComfyUI-3D-Pack/js/threeVisualizer.js TypeError：无法解析模块说明符“three”。相对引用必须以 “/”、“./” 或 “../".
> 
> ![Screenshot 2024-08-31 214325](https://github.com/user-attachments/assets/4d8ce1ed-0e3c-4627-b648-4d3f5a1a23fb) ![image](https://github.com/user-attachments/assets/71419824-ba7c-4467-b215-cd0e6ba61e69)

我也遇到了一摸一样的问题，楼主解决了吗
