### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 2)

### ISSUE THREAD

**Issue by xiwan** [MrForExample/ComfyUI-3D-Pack#3]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/ComfyUI/execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/ec2-user/SageMaker/ComfyUI/execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/ec2-user/SageMaker/ComfyUI/execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/ec2-user/SageMaker/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 334, in run_3DGS
    gs.training()
  File "/home/ec2-user/SageMaker/ComfyUI/custom_nodes/ComfyUI-3D-Pack/gaussian_splatting/main_3DGS.py", line 163, in training
    out = self.renderer.render(ref_cam, bg_color=bg_color)
  File "/home/ec2-user/SageMaker/ComfyUI/custom_nodes/ComfyUI-3D-Pack/gaussian_splatting/main_3DGS_renderer.py", line 1044, in render
    rendered_image, radii, rendered_depth, rendered_alpha = rasterizer(
ValueError: not enough values to unpack (expected 4, got 2)

Above is the error, this was casue by the calling:

```
rendered_image, radii, rendered_depth, rendered_alpha = rasterizer(
            means3D=gaussians_xyz,
            means2D=screenspace_points,
            shs=shs,
            colors_precomp=colors_precomp,
            opacities=gaussians_opacity,
            scales=gaussians_scales,
            rotations=gaussians_rotations,
            cov3D_precomp=cov3D_precomp,
        )

```

looks like only return 2 values but required is 4.

How to fix it? thanks in advance

**Comment by MrForExample** [comment]
Sorry, I don't have enough information to determine what's the problem, are you running the example workflow & data I provided? or did you change the inputs data? If so, may I have a screen shot of your workflow pls?

Thanks for testing! I'll make those edge case detection more restrict 👍

**Comment by xiwan** [comment]
<img width="1440" alt="Screenshot 2024-01-10 at 14 24 23" src="https://github.com/MrForExample/ComfyUI-3D-Pack/assets/931632/6fa8fda2-fa47-4b4b-aa1f-f72e59a61b47">

worklow name: 3DGS_Multi-View_Renders_to_ply
 I didn't change any inputs

**Comment by MrForExample** [comment]
Sorry, I couldn't reproduce the error you got, could you pull the newest change set and use this [example workflow] (https://github.com/MrForExample/ComfyUI-3D-Pack/blob/main/_Example_Workflows/Using_Stack_Orbit_Camera_Poses_to_conditioning_StableZero123.json)
And see if error still exist?

Please make sure to copy all the example inputs into ComfyUI's input directory 👍

**Comment by xiwan** [comment]
Good news: the orbit camera workflow has no error. 
Bad news: 3DGS_Multi-View_Renders_to_ply still complains the same not enough value error!

my env: 
*A10 linux machine, notebook
*PyTorch 2.0.1
*Python  3.10.13

**Comment by MrForExample** [comment]
Thanks for testing and letting me know, I'll do a double check on that 👍 

Is there other functionality or algorithm you think will benefit most people that you know who are using ComfyUI?

**Comment by MrForExample** [comment]
Oh! 😁
I know why you got that error, I saw your [another comment](https://github.com/MrForExample/ComfyUI-3D-Pack/issues/1#issuecomment-1882366583) where you suggested to install the [original Differential Gaussian Rasterization](https://github.com/graphdeco-inria/gaussian-splatting), so I assume that you also installed the original one, but this project, as state in readme, used a [updated version of Differential Gaussian Rasterization](https://github.com/ashawkey/diff-gaussian-rasterization) which supports depth & alpha rendering (both forward and backward), and that is exactly what error trying to tell us what is missing!

So to fix this, delete the original Differential Gaussian Rasterization, and install & build a new one using:

```bash
git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization
pip install ./diff-gaussian-rasterization
```

Let me know if there is any other issue 👍

**Comment by xiwan** [comment]
Very nice, i will test it. 
BTW, your work is really cool!

**Comment by xiwan** [comment]
This is my working installation steps:
`
!git clone --recursive https://github.com/NVlabs/nvdiffrast
!git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization
!git clone --recursive https://github.com/facebookresearch/pytorch3d

!pip install ./diff-gaussian-rasterization
!pip install ./gaussian-splatting/submodules/simple-knn
!pip install ./nvdiffrast
!pip install ./pytorch3d
`

**Comment by MrForExample** [comment]
Glad to hear this issue is solved!
