### ISSUE TITLE
Force install torch==2.4.0?

### ISSUE THREAD

**Issue by tanGuangYao** [MrForExample/ComfyUI-3D-Pack#319]
In my Python environment, I already have PyTorch 2.3.1+cu121 
 every time I start, ComfyUI-3D-Pack always tries to install torch==2.4.0.

![Snipaste_2024-09-27_22-02-42](https://github.com/user-attachments/assets/2894d222-271e-43c6-b77c-787cdab4dd0f)

What causes this issue? Right now, I can only resolve it by renaming the install.py and requirements.txt files.

**Comment by tanGuangYao** [comment]
![Snipaste_2024-09-27_22-06-31](https://github.com/user-attachments/assets/6e626388-0d00-41ab-a6fc-1655053efcf6)


Also, the UI is distorted.

**Comment by jakechai** [comment]
Please look at this:
https://github.com/MrForExample/ComfyUI-3D-Pack/issues/306#issuecomment-2356620009
https://github.com/MrForExample/ComfyUI-3D-Pack/issues/306

**Comment by comfyui-liaohui** [comment]
我为什么不行，麻烦帮助我
![屏幕截图 2024-09-29 015716](https://github.com/user-attachments/assets/5ccc41b4-7f22-4829-a9ed-baf4afda690f)

**Comment by comfyui-liaohui** [comment]
Why not me? Please help me. I am Chinese.
![Uploading 屏幕截图 2024-09-29 015716.png…]()

**Comment by MrForExample** [comment]
Hi all, I just updated the [pre-builds](https://github.com/MrForExample/Comfy3D_Pre_Builds) for 
`Windows; Python 3.10, 3.11, 3.12; pytorch 2.5.0, torchvision 0.20.0, xformer 0.28.0 post2`
Hope you had a good weekend :)
