### ISSUE TITLE
why i always need to download or fetch files when i run the example workflow?

### ISSUE THREAD

**Issue by JimWang151** [MrForExample/ComfyUI-3D-Pack#327]
I load example workflow from the '_Example_Workflows' ,but every time,when i run the workflow,always tell me need to download the model file.I know that some node need to set the option 'force_download' into 'True',but why i always need to download the model file every time?
Below is the download nodes :
![image](https://github.com/user-attachments/assets/3af367d2-d1bb-4ec1-9d5a-faddca44281e)

The workflow is: **_Unique3D_with_Era3D_All.json_**
Screen shot of the workflow: 
![image](https://github.com/user-attachments/assets/b534cb5f-6eb5-4f9f-8e06-e383fdcbc2da)

Always downloading like this:

![image](https://github.com/user-attachments/assets/062b5f8a-6da8-45c3-88dd-9f4f5509037e)

Can u tell my why?Thanks for your help.

**Comment by JimWang151** [comment]
I checked the model file 'checkpoints' stored in 'ComfyUI-3D-Pack',and i think all the models have been download,the capacity of the 'checkpoints' has reached '70G',but why i need to download again and again when i run the workflow?

Structure of the folder 'checkpoints'
![image](https://github.com/user-attachments/assets/fa706cbc-09ea-4ed4-9276-dbf0de3322e0)

And the capacity of the foleder 'checkpoints'
![image](https://github.com/user-attachments/assets/37afcd59-4e64-4bbf-9369-70090a59b507)
 
Thanks for your care.

**Comment by JimWang151** [comment]
Now i am running the example workflow of :**_Unique3D_with_Era3D_All.json_**

Still need to download the model file showed below:

![image](https://github.com/user-attachments/assets/b6f121b2-4ca0-4c89-82e0-aa40f9f55823)

![image](https://github.com/user-attachments/assets/5528398d-eea2-420d-b475-1ec1f8464e47)

**_This is not the first time i run this workflow!!!_**

**Comment by JimWang151** [comment]
Below is the Structure of 'MrForExample/Unique3D' stored in the 'checkpoints' folder:

![image](https://github.com/user-attachments/assets/5db7be8c-7ff1-4b94-b92d-101add311e52)

The capacity of Unique3D:
![image](https://github.com/user-attachments/assets/a71ef885-ac76-4523-b018-f156f78d329a)

Did i miss something?

**Comment by JimWang151** [comment]
This cost me lots of time.

**Comment by JimWang151** [comment]
I got the key.This issue can be closed.
Thanks.

**Comment by rob-ack** [comment]
Just in case you havnt. Also keep in mind to uncheck the 'force_download' flag in your Load Pipeline node to not redownload the model all the time.
