### ISSUE TITLE
3 or 4 3d image view instead of one

### ISSUE THREAD

**Issue by kakachiex2** [MrForExample/ComfyUI-3D-Pack#33]
It is possible to use generate image view instead of one to get a more detailed model for example see this model on Civita I think create a workflow with this approach will be much accurate to use only one image view :
- Civitai Lora : https://civitai.com/models/291056/fn-collectionipxl-creative-three-views
- Some examples : 
- 
![04785-1287753445-IP,anime characters,slim figure,hand version style,girl,Three views,_lora_FN-CollectionIP_XL-V1 0_0 8_,lace short-sleeve top,(Pr](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/1762112/b87e5b0f-80fc-42bd-894b-2e22ff5c96ec)
![00319-1948818482](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/1762112/5978e991-53a4-481d-9442-62fe9c0efbd8)
![04755-680405229-front,back,side,three view,glass mimicry,girl,glass mimicry ip,describe this image in a very detailed manner  a 3d-rendered char](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/1762112/6182da63-0dee-4f2c-ae4c-02d2c75d25a0)

**Comment by kakachiex2** [comment]
I'm a 3D Modeler and I found this really interesting specially if I create my own sketch character render it in ComfyUI and generate all the views them generate the 3d model send to Blende and sculpt all details this will be the ultimate workflow..

**Comment by kakachiex2** [comment]
what is the ideal size this model support 512, 768 or...?

**Comment by MrForExample** [comment]
Hi, friend, you can use your own images of 4 angles as [others have already asked](https://github.com/MrForExample/ComfyUI-3D-Pack/issues/26):
Just make input images square, the node will automatically resize the image to the correct input size, for LGM is 256X256
Nice looking images by the way ;)

**Comment by kakachiex2** [comment]
Thanks for your reply
