### ISSUE TITLE
"PriestCat.png" is missing from the input folder.

### ISSUE THREAD

**Issue by GPU-server** [MrForExample/ComfyUI-3D-Pack#338]
There is no PriestCat.png here: https://github.com/MrForExample/ComfyUI-3D-Pack/tree/main/_Example_Workflows/_Example_Inputs_Files

**Comment by MrForExample** [comment]
Hi, thanks for pointed it out, however there is PirateCat_0.png in the folder, I'll rename it today, cheers 👍
