### ISSUE TITLE
"README.md file." is missing (BROKEN LINK) from the docker instructions.

### ISSUE THREAD

**Issue by GPU-server** [MrForExample/ComfyUI-3D-Pack#340]
On this page:
https://github.com/MrForExample/ComfyUI-3D-Pack/blob/main/DOCKER_INSTRUCTIONS.md
Paragraphe:

"These instructions are focused on running the Unique3D workflows, you can use the same steps to run the other workflows, but you need to check the model requirements for each workflow at the **README.md** file."

The page "README.md" lead to a 404 - Page Not Found.

**Comment by MrForExample** [comment]
Hi, thanks for pointing out, I'll fix it today, cheers 👍

**Comment by GPU-server** [comment]
Np since I have you here @MrForExample , I want to tell you that your custom node, gave me nightmares. I spent severaldays trying to make it work without any error. I even learned to debug many errors. Did not achieve full success btw lol. Anyway. WIll comme back to it in the future (for sure).

**Comment by MrForExample** [comment]
@GPU-server 
Haha, yeah, I know install is still a pain for some people, although I tried my best to make it as automatic as possible, but it's hard to build a product level solution when I have to work full time at both R&D and manage a team, in time it will get better through community effort.
Cheers my friend, see you around, and have a good weekend 👍
