### ISSUE TITLE
One very frustrating problem with this Extension no ONE TALKS ABOUT : Every time you install missing nodes from OTHER extensions, it results in breaking ComfyUI.

### ISSUE THREAD

**Issue by GPU-server** [MrForExample/ComfyUI-3D-Pack#341]
I battled for hours and days trying to make this work, I finally was able to make one of the 3D pack workflows work. Moved to the next workflow only to see it has nodes from other extensions. I press : install missing nodes, restart comfy and the logs show:

**Attempting uninstall: torch
     Found existing installation: torch 2.4.0+cu121
     Uninstalling torch-2.4.0+cu121:
       Successfully uninstalled torch-2.4.0+cu121**

Adn later one:

**raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled**

ComfyUI does not start anymore !
This happens almost EVERY time I install missing nodes from other extensions!

__
All of this because I installed torch 2.4.0 cuda 121, on a comfyUI installation that comes initially with a 2.4.1 version.

**Comment by MrForExample** [comment]
Hi @GPU-server, I just updated the [pre-builds](https://github.com/MrForExample/Comfy3D_Pre_Builds) for 
`Windows; Python 3.10, 3.11, 3.12; pytorch 2.5.0, torchvision 0.20.0, xformer 0.28.0 post2`
Hope you had a good weekend :)

**Comment by GPU-server** [comment]
Thanks, how do you do it btw?
