### ISSUE TITLE
Error occurred when executing [Comfy3D] Era3D MVDiffusion Model：

### ISSUE THREAD

**Issue by CYHANG123** [MrForExample/ComfyUI-3D-Pack#345]
Error occurred when executing [Comfy3D] Era3D MVDiffusion Model:

to() received an invalid combination of arguments - got (torch.dtype, torch.device), but expected one of:
* (torch.device device = None, torch.dtype dtype = None, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
* (torch.dtype dtype, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
* (Tensor tensor, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)

File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 316, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 191, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 168, in _map_node_over_list
process_inputs(input_dict, i)
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 157, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 2589, in run_model
multiview_images = images_pred.permute(0, 2, 3, 1).to(reference_image.dtype, reference_image.device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by MrForExample** [comment]
Hi, thanks for point it out, I'll fix it today, cheers 👍

**Comment by JasonS09** [comment]
Is this fixed? I'm still facing this issue

**Comment by amir84ferdos** [comment]
any idea how to solve this problem?

**Comment by amir84ferdos** [comment]
I found the problem, replaced it on lines 2589 and 2590 in nodes.py
 multiview_images = images_pred.permute(0, 2, 3, 1).to(dtype=reference_image.dtype, device=reference_image.device)   
 multiview_normals = normals_pred.permute(0, 2, 3, 1).to(dtype=reference_image.dtype, device=reference_image.device)
 
 ************
