### ISSUE TITLE
Unique3d workflow, missing "lambdalabs/sd-image-variations-diffusers" when loading "Unique3D\image2normal" model.

### ISSUE THREAD

**Issue by 105158317** [MrForExample/ComfyUI-3D-Pack#354]
I am running "ComfyUI-3D-Pack\_Example_Workflows\Unique3D\Unique3D_All_Stages.json" workflow, when it runs to stage_3 and loading the model "image2normal", I got a error **"OSError: lambdalabs/sd-image-variations-diffusers does not appear to have a file named config.json."**. owing to my country's internet-block policy, my Comfyui can't downloaded automatically the files of "lambdalabs/sd-image-variations-diffusers", so I download them manually, but I don't know where the folder should the files be put into.  
  I have checked the related issues about "lambdalabs/sd-image-variations-diffusers", but I failed to solve this problem, any idea to help? much much thanks.
  
  
![1](https://github.com/user-attachments/assets/0a61771d-5561-4974-b109-0841b4abc06c)

![2](https://github.com/user-attachments/assets/8094893d-9003-40b0-b3a4-c34b280b31bb)

![3](https://github.com/user-attachments/assets/5fd8720a-eb84-4508-b85f-68459f642ca9)

**Comment by 105158317** [comment]
allright, I made it by a inappropriate way..

**Comment by JamesLooo** [comment]
How did you do it？
