### ISSUE TITLE
It would be great if Hunyuan3d-1 is supported

### ISSUE THREAD

**Issue by xiongwenxin123** [MrForExample/ComfyUI-3D-Pack#361]
The  Tencent's new Hunyuan3d-1 model is more accurate. I hope the author can add support。

**Comment by MrForExample** [comment]
Did just that, give a try my friend 👍

**Comment by xiongwenxin123** [comment]
I am trying use nodes in my workflow, but how do I change the maximum number of mesh faces in hunyuan3d-1 node?

**Comment by MrForExample** [comment]
Hi @xiongwenxin123 sorry for the late responds
I'll expose this parameter in next release soon, along with new [TRELLIS](https://github.com/microsoft/TRELLIS) model.
Cheers 👍
