### ISSUE TITLE
SF3D model load node execute error: fatal error C1083: 无法打开包括文件: “slang.h”: No such file or directory

### ISSUE THREAD

**Issue by coddz** [MrForExample/ComfyUI-3D-Pack#376]
comfyui console message can see the attachfile:
[comfy3d_log.txt](https://github.com/user-attachments/files/17848690/comfy3d_log.txt)

**Comment by coddz** [comment]
maybe torch c++ extension cannot find the slang.h.

comfyui 0.3.0(python 3.12 torch2.5.1cu124)
visual studio cummunity 2022 with c++ desktop 
cuda 12.6

others: ComfyUI-3D-Pack and it's preBuilds whl

**Comment by coddz** [comment]
comfyui 3d pack can run triposr and hunyuan3d v1 and running Stable Fast 3D model load node raise the error.

**Comment by MrForExample** [comment]
Seems the issue is same as in [issues/383](https://github.com/MrForExample/ComfyUI-3D-Pack/issues/383)
