### ISSUE TITLE
Dear MrForExample, just post the py env list

### ISSUE THREAD

**Issue by Corshi** [MrForExample/ComfyUI-3D-Pack#377]
As in the title.
For clean `python`, with `pip` and `easy_install` installed run:
`pip freeze > my-reqs.txt`
or for `conda` run:
`conda list --explicit > environment_backup.txt`

and give use the list.

With an amazing extension like this, it is still hard to get what packages and other things are necessary and should be obvious to us.

**Comment by MrForExample** [comment]
Hi @Corshi, sorry for the late responds
That's good idea, I will add one to make manual install easier!
Have a good day👍
