### ISSUE TITLE
 FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.   @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

### ISSUE THREAD

**Issue by stromyu520** [MrForExample/ComfyUI-3D-Pack#381]
D:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-23 21:15:34.197024
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\AI\ComfyUI_windows_portable\ComfyUI
** Log path: D:\AI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.8 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8188 MB, total RAM 32469 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: D:\AI\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path checkpoints E:\dev\pythonProject\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs E:\dev\pythonProject\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae E:\dev\pythonProject\stable-diffusion-webui\models/VAE
Adding extra search path loras E:\dev\pythonProject\stable-diffusion-webui\models/Lora
Adding extra search path loras E:\dev\pythonProject\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models E:\dev\pythonProject\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models E:\dev\pythonProject\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models E:\dev\pythonProject\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings E:\dev\pythonProject\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks E:\dev\pythonProject\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet E:\dev\pythonProject\stable-diffusion-webui\models/ControlNet
D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kiui\nn\__init__.py:31: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kiui\nn\__init__.py:37: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_bwd

D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\utils\ops.py:38: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float32)

D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\utils\ops.py:44: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd

Warn!: xFormers is available (Attention)
Warn!: D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(

Warn!: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\craftsman\utils\checkpoint.py:39: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd

Warn!: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\craftsman\utils\checkpoint.py:50: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_bwd

**Comment by MrForExample** [comment]
Hi @stromyu520, noted, I'll update this to avoid future error, cheers 👍

**Comment by stromyu520** [comment]
> 你好@stromyu520，注意，我会更新此内容以避免将来出现错误，谢谢👍

ok
