### ISSUE TITLE
StableFast3D/CharacterGen/CRM raise error and I tested triposr/hunyuan3d-1/StableFast3D/CharacterGen/CRM/TriplaneGaussian

### ISSUE THREAD

**Issue by coddz** [MrForExample/ComfyUI-3D-Pack#383]
example in _Example_Workflows:
triposr     OK
hunyuan3d-1   OK
TriplaneGaussian   OK

StableFast3D     can not find the slang.h 
CharacterGen    ...
CRM                  ...
InstantMesh      ...
Unique3D          ...

Thank you, MrForExample. 

I am happy to use triposr/hunyuan3d/TriplaneGaussian and will hope the new ComfyUI-3D-Pack.

**Comment by ThankyouF** [comment]
"pip install -v slangtorch==1.2.6"
I also met this before and this solved my problem

**Comment by MrForExample** [comment]
Hi @coddz sorry for the late responds
slangtorch seems already in requirements.txt, I'll take deeper look before next release, cheers 👍
