### ISSUE TITLE
Installation tutorial for the releases

### ISSUE THREAD

**Issue by Mikerhinos** [MrForExample/ComfyUI-3D-Pack#385]
I know I'm not a senior software engineer, but this is the 1st time I struggle so much to install something in my life... :(

I'm on Win10,  RTX4070Ti Super 16GB and 32GB RAM.
I downloaded the latest custom node release, which is 0.1.2
It says "Support newest ComfyUI v0.2.7, py12, cu124, torch 2.5.1", so I downloaded ComfyUI v0.2.7 portable version which installs Python 3.12 and Torch 2.5.1 with Cuda 12.4
I just spent a whole day trying to get ComfyUI-3D-Pack installed, using ChatGPT and Claude to help me :(
I'm now stuck at "ModuleNotFoundError: No module named 'pytorch3d'" and can't find a way to install it (normal package, specific version package, prebuilt wheel, compiled wheel).

The pack looks awesome, and I really want to play with it, but man it's so complicated to install :( (previously I tried on my "personal" local ComfyUI Github installation I have since like 2 years, then a fresh ComfyUI Github install).

So if you or anyone could write a tutorial on how to install the latest pack version it would be awesome !

**Comment by gioxyer** [comment]
For  pytorch3d you need to install prebuild that contains all the packages that ComfyUI 3D needs:
https://github.com/MrForExample/Comfy3D_Pre_Builds

On Code section use download zip:

![immagine](https://github.com/user-attachments/assets/fb2464c8-08fa-4aeb-9666-380defe6a86c)

Then extract the file in any location do you want:

![immagine](https://github.com/user-attachments/assets/eead3c96-b119-4388-9788-d38de7159037)

After that goes into _Build_Wheels

![immagine](https://github.com/user-attachments/assets/03726628-f354-4e54-8add-dea78ac8c2a8)

Then scroll down until you find your version, in this case 2.5.1+cu124:

![immagine](https://github.com/user-attachments/assets/91f271b9-d97c-413a-bc6c-b76f34f22b88)

Open 2.5.1+cu124 folder and you will find pytorch3d:

![immagine](https://github.com/user-attachments/assets/fc69cd6d-1f32-4980-b225-efb7cb45aba6)

Keep this explorer tab open and do another in ComfyUI:

![immagine](https://github.com/user-attachments/assets/7dcf74e3-90ea-4b1a-9a69-d47df2043526)

Goes into python_embeded as path **ComfyUI_windows_portable\python_embeded**

![immagine](https://github.com/user-attachments/assets/698a6b21-d712-4eca-94fe-dc3514ed65c1)

Scroll down until you find python.exe and copy its path:

![Screenshot (63)](https://github.com/user-attachments/assets/1f863b89-5725-4ff8-823f-aa0415952180)

Then inside this folder on path type cmd and enter:

![immagine](https://github.com/user-attachments/assets/6b99194d-549a-4604-b7bf-e93e4329c07f)

It will appears with _**C:\Users\giorg\Documents\ComfyUI_windows_portable\python_embeded>**_

![immagine](https://github.com/user-attachments/assets/00730c0d-f15c-4f4f-8fb6-e9cc86d83d92) and you will paste your python's path _**"C:\Users\giorg\Documents\ComfyUI_windows_portable\python_embeded\python.exe"**_

After that type -m pip install:

![immagine](https://github.com/user-attachments/assets/fd69bbd4-ea82-46c0-85fc-98937c7fd7ee)

Then you should go into PreBuild folder and copy path of the package you need, in this case pythorc3d:

![Screenshot (65)](https://github.com/user-attachments/assets/0c273bb4-d270-4959-b855-8a5a667870c8)

Then copy into CMD, remember to give space to all the path that you copy:

<img width="860" alt="Immagine 2024-11-28 075032" src="https://github.com/user-attachments/assets/3b580e3e-4d3a-4c9d-b1a2-867c325bf5d6">

Press enter and it should install correctly, to verify that check what CMD say:

![immagine](https://github.com/user-attachments/assets/f09e3529-a26c-4bf1-b359-d1e2c28811eb)

Hope can help, let me know

**Comment by Mikerhinos** [comment]
Thanks, I installed the prebuilt wheel, then had a onnxruntime not found so I installed onnxruntime-gpu, then I got a Python.h error thing and was just fed up after 3 days so luckily I found this https://github.com/MrForExample/ComfyUI-3D-Pack/issues/333#issuecomment-2402546163 , installed a portable ComfyUI with pre installed ComfyUI-3D-Pack, it worked right away.
I launched a Hunyuan workflow as it's the one interesting me now, had some red nodes so I "Try Update" ComfyUI-3D-Pack in the Manager, restarted, and it seems to be fixed.

So for anyone that doesn't want to spent a lot of time on installing or is stuck, I'd say go for the portable pre installed solution.

**Comment by Kallamamran** [comment]
Installing Pytorch3d worked now in a new Comfy env... Though adding 3D-Pack through Manager:

![image](https://github.com/user-attachments/assets/7bf3b344-9c83-4653-a063-759efb70fbc9)

And then when trying in cmd-window:

![image](https://github.com/user-attachments/assets/c881652b-6ee3-4b94-acd9-f26968d3cd61)
