### ISSUE TITLE
 Value not in list: control_net_name: 'control_unique3d_sd15_tile.safetensors' not in ['diffusion_pytorch_model.safetensors', 'sai_xl_depth_256lora.safetensors']

### ISSUE THREAD

**Issue by victorgaozhan** [MrForExample/ComfyUI-3D-Pack#387]
When I run the "Quque Prompt" after loading an image, the cmd system prompted:

Failed to validate prompt for output 289:
* ControlNetLoader 192:
  - Value not in list: control_net_name: **'control_unique3d_sd15_tile.safetensors'** not in ['diffusion_pytorch_model.safetensors', 'sai_xl_depth_256lora.safetensors']
Output will be ignored
Failed to validate prompt for output 195:
Output will be ignored
Failed to validate prompt for output 277:
Output will be ignored
Failed to validate prompt for output 299:
Output will be ignored
....
Output will be ignored
Failed to validate prompt for output 288:
Output will be ignored。
It just finished when finishing stage_1 but not running stage 2~4.

**Comment by MrForExample** [comment]
Hey @victorgaozhan sorry for the late responds
It seems you don't have [control_unique3d_sd15_tile.safetensors](https://huggingface.co/spaces/Wuvin/Unique3D/tree/main/ckpt/controlnet-tile) in your corresponding model dir.
Download it and put it under `Your ComfyUI root directory/ComfyUI/models/controlnet`, for more info about Unique3D and each model, please check [README](https://github.com/MrForExample/ComfyUI-3D-Pack/blob/main/README.md)
