### ISSUE TITLE
Implement huanngzh/MV-Adapter

### ISSUE THREAD

**Issue by NeuroLord** [MrForExample/ComfyUI-3D-Pack#389]
A model for generating multiview images from text and a single image was recently released and its generation results are delightful. It's based on SDXL with 768p resolution and can generate up to 40 views! 
If this could be natively implemented in Comfy3D, it would rub the nose of (probably) all commercial 3D model generators.
https://github.com/huanngzh/MV-Adapter

**Comment by MrForExample** [comment]
@NeuroLord Hi, about that addon model, I saw they already have a ComfyUI implementation, also, from my testing, I don't think their result is any better than Era3D which is already in Comfy3D, so I think it's better for me to use my time on something else, cheers 👍
