### ISSUE TITLE
'NoneType' object has no attribute 'v'

### ISSUE THREAD

**Issue by msskaa12** [MrForExample/ComfyUI-3D-Pack#4]
Thanks for this awesome work ,buddy ！

when I test the  "Bake_Multi-View-Renders_into_UV_Texture.json" example file ,   error message pop up  and stopped at   "Bake Texture To Mesh" node, the error message is bellow:

AttributeError: 'NoneType' object has no attribute 'v'

  File "/home/young/Github/ComfyUI/execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/young/Github/ComfyUI/execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/young/Github/ComfyUI/execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/young/Github/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 399, in bake_texture
    texture_baker = DiffTextureBaker(reference_images, reference_masks, reference_orbit_camera_poses, reference_orbit_camera_fovy, mesh,
  File "/home/young/Github/ComfyUI/custom_nodes/ComfyUI-3D-Pack/diff_rast/diff_texturing.py", line 29, in __init__
    self.renderer = Renderer(mesh, force_cuda_rasterize).to(self.device)
  File "/home/young/Github/ComfyUI/custom_nodes/ComfyUI-3D-Pack/diff_rast/diff_mesh_renderer.py", line 53, in __init__
    self.v_offsets = nn.Parameter(torch.zeros_like(self.mesh.v), requires_grad=True)
AttributeError: 'NoneType' object has no attribute 'v'

"3DGS_Multi-View_Renders_to_ply.json"  work success.

___
OS: ubuntu20.04 
Pytoch:2.1.2
pytorch3d-0.7.5
cuda118
python 3.10

**Comment by MrForExample** [comment]
This error means there is no mesh provided to Bake Texture To Mesh node, I also provided a Cammy_Uniform.obj mesh file under https://github.com/MrForExample/ComfyUI-3D-Pack/tree/main/_Example_Workflows/_Example_Inputs_Files
As I mentioned in the readme, You need to copy those two folders under ComfyUI_windows_portable(Your ComfyUI root dir)\ComfyUI\input 

Thanks for testing, I'll make the error message more clear! Let me know how it goes 👍

**Comment by msskaa12** [comment]
> This error means there is no mesh provided to Bake Texture To Mesh node, I also provided a Cammy_Uniform.obj mesh file under https://github.com/MrForExample/ComfyUI-3D-Pack/tree/main/_Example_Workflows/_Example_Inputs_Files As I mentioned in the readme, You need to copy those two folders under ComfyUI_windows_portable(Your ComfyUI root dir)\ComfyUI\input
> 
> Thanks for testing, I'll make the error message more clear! Let me know how it goes 👍

I had copy this two floder  under ComfyUI\input

**Comment by msskaa12** [comment]
and I had update pytorch version to 2.1.2 , the problem is same

**Comment by msskaa12** [comment]
I got it , I move out the file "Cammy_Uniform.obj" frome "mesh" folder , and rename the " mesh_file_path " , it works .
thanks your reply
