### ISSUE TITLE
Stuck on Convert 3DGS to Mesh with NeRF and Marching Cubes

### ISSUE THREAD

**Issue by DeepSkyObjects** [MrForExample/ComfyUI-3D-Pack#40]
The project works good but I have some issues with the node called [Comfy3D] Convert 3DGS to Mesh with NeRF and Marching Cubes. For some reason it get stuck on [Comfy3D] Convert 3DGS to Mesh with NeRF and Marching Cubes and never pass this node. 

If I remove this node and just check the preview 3DGS then it runs without any issues.

There arent any errors in the commandline.

Running it on one of my 3090s so memory shouldnt be any issue.

Any ideas of what causing it?

**Comment by BizaNator** [comment]
I believe I was able to resolve that issue by installing Build Tools for Visual Studio 2019
https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017

I'm not sure if it's related but previously I had to also install Ninja - https://github.com/MrForExample/ComfyUI-3D-Pack/issues/32#issuecomment-1943206856

**Comment by DeepSkyObjects** [comment]
Did you have any issues during install or was this just related to the process later on?

Im using visual studio 2022 on a daily basis and have build tools installed for it.
Ninja is already installed.

**Comment by MrForExample** [comment]
This could very likely be torch lock issue: [Code Hangs Indefinitely When Evaluating Neuron Models on GPU](https://github.com/lava-nc/lava-dl/discussions/211)

**Comment by DeepSkyObjects** [comment]
> This could very likely be torch lock issue: [Code Hangs Indefinitely When Evaluating Neuron Models on GPU](https://github.com/lava-nc/lava-dl/discussions/211)
I printed the cache folder from the torch cpp_extension and  deleted the cache directory under appdata\local\torch_extension.... but the issue still exist :(.

Any other clues?

**Comment by tcarneyjohnson** [comment]
Hello, I’ve been trying to resolve what seems to be the same issue for a little while now.

I’ve read through the forum conversation that is provided as a link above, but I’m not clear on the location of the cache in question.

I’m on Windows 10 and have tried deleting the folder C:\Users\MyUserName\.cache to no avail.

Can you please provide me with more specific information about the location of the folder in question?

Thank you!

**Comment by tcarneyjohnson** [comment]
In case this helps anyone: on my Windows 10 machine this folder was located under C:\Users\MyUserName\AppData\Local\torch_extensions. After deleting these files, the conversion started working after a slightly delayed start.
