### ISSUE TITLE
Trellis - 3090 , Allocation on device

### ISSUE THREAD

**Issue by siraxe** [MrForExample/ComfyUI-3D-Pack#401]
Win11
Python version: 3.12.0 
Total VRAM 24576 MB, total RAM 65366 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention

![image](https://github.com/user-attachments/assets/f54b2104-65d0-46b3-b189-ebcddfa05b59)
![image](https://github.com/user-attachments/assets/cf662ef8-0ff4-4137-9295-766fc0c840b6)

Tried multiple rebuilds etc , got to this point so far...
Not really sure what else to do , maybe some version of something is not compatible ?

**Comment by siraxe** [comment]
it was prebuild `diff_gaussian_rasterization`
https://github.com/MrForExample/ComfyUI-3D-Pack/issues/171#issuecomment-2347917882

**Comment by siraxe** [comment]
I take that back , something is still broken 
![firefox_LFFKglQcYP](https://github.com/user-attachments/assets/9791217a-5e0d-4e93-9d6c-55e8c85d847f)
![firefox_iaG3Oo2ppS](https://github.com/user-attachments/assets/212413f2-c260-4dff-8927-ab2472224d33)

**Comment by siraxe** [comment]
ah , had to invert the mask
![image](https://github.com/user-attachments/assets/e9387e77-6c1a-4167-be8f-2679d957e7de)

**Comment by alexisrolland** [comment]
@siraxe I also have a 3090 with 24Gb of vRAM and facing the `Allocation on device` memory issue...

```
[...]
 File "D:\alexis\ComfyUI\python_embeded\Lib\site-packages\diff_gaussian_rasterization\__init__.py", line 92, in forward
    num_rendered, color, depth, alpha, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Allocation on device
```

How did you solve it please?
