### ISSUE TITLE
what visual studio components should be installed?

### ISSUE THREAD

**Issue by nikolaiusa** [MrForExample/ComfyUI-3D-Pack#49]
please help)

**Comment by MrForExample** [comment]
Hi, which way of install you are using? If you install it using Miniconda or Chocolatey  then you don't have to install it manually.

**Comment by nikolaiusa** [comment]
i use windows10 +  miniconda and i cant build wheels - 
i have error like this:    
   build\lib.win-amd64-cpython-311\pointnet2_ops\_ext.cp311-win_amd64.pyd : fatal error LNK1120: : 101
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe' failed with exit code 1120
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pointnet2-ops

**Comment by nikolaiusa** [comment]
build\lib.win-amd64-cpython-311\torch_scatter\_scatter_cpu.pyd : fatal error LNK1120:: 38
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter

Failed to build pointnet2-ops simple-knn diff-gaussian-rasterization pytorch3d torch-scatter

ERROR: Could not build wheels for pointnet2-ops, simple-knn, diff-gaussian-rasterization, pytorch3d, torch-scatter, which is required to install pyproject.toml-based projects

**Comment by nikolaiusa** [comment]
i can build wheels for this 5: pointnet2-ops simple-knn diff-gaussian-rasterization pytorch3d torch-scatter

**Comment by nikolaiusa** [comment]
I used this instruction https://github.com/MrForExample/ComfyUI-3D-Pack/issues/22#issuecomment-1937795756

**Comment by nikolaiusa** [comment]
oh god, I installed it)
I installed Anaconda instead of MiniConda. and received more information about the errors

**Comment by MrForExample** [comment]
Glad you did it, cheers friend, I'll note it in the install instruction in next update 👍
