### ISSUE TITLE
Notes about compiling the dependencies

### ISSUE THREAD

**Issue by doctorpangloss** [MrForExample/ComfyUI-3D-Pack#5]
These instructions can be adapted to compile your requirements and avoid using `miniconda` on Windows.

```bash
# using git bash for the sake of simplicity
# enable developer mode
# google this: allow os.symlink on windows by adding your username to the local security policy entry for it.
# you will have to restart your computer
# install chocolatey using powershell, then install the prereqs for compilation on Windows
choco install -y visualstudio2022buildtools
choco install -y visualstudio2022-workload-vctools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset --add Microsoft.VisualStudio.Component.VC.Llvm.Clang"
choco install -y cuda

# now clone threestudio
git clone git@github.com:threestudio-project/threestudio.git
cd threestudio/
python -m venv venv
source venv/scripts/activate
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121
# include missing dependencies from their repo
pip install ninja wheel mediapipe
pip install -r requirements.txt --no-build-isolation
# you will watch nerfacc and tiny-cuda compile for a while
# download stable_zero123.ckpt from https://huggingface.co/stabilityai/stable-zero123 and put it into ./load/zero123
# run. modify your configs/stable-zero123.yaml data.random_camera.batch_size, trainer.precision and trainer.gradient_accumulation_steps for much better performance
python launch.py --config configs/stable-zero123.yaml --train --gpu 0 data.image_path=./load/images/hamburger_rgba.png
```

**Comment by MrForExample** [comment]
Thanks friend.
So from what I can tell, this is a windows only solution, and basically using one package manager (**Chocolatey**) to replace another (**Miniconda**).
But still, thanks for a different solution, I'll add it into install guide soon since some user may find this solution helpful :)
Cheers 👍

**Comment by doctorpangloss** [comment]
> Thanks friend.
> 
> So from what I can tell, this is a windows only solution, and basically using one package manager (**Chocolatey**) to replace another (**Miniconda**).
> 
> But still, thanks for a different solution, I'll add it into install guide soon since some user may find this solution helpful :)
> 
> Cheers 👍 

lol okay good point. But installing visual studio via its setup is really complicated. chocolatey is comparable to apt not miniconda. Overall blame Microsoft, not me.

**Comment by ZZXYWQ** [comment]
where I build this venv
