### ISSUE TITLE
Error with Multi-View Images to 3DGS to 3DMesh

### ISSUE THREAD

**Issue by PunishMints** [MrForExample/ComfyUI-3D-Pack#56]
When using the example workflow provided for multi-view images to 3D, I get this error on the "Gaussian Splatting" Node:

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Gaussian_Splatting.run_gs() missing 1 required positional argument: 'loss_value_scale'
```

I've installed 3D-Pack with miniconda, but I had to change where gridencoder looks for VS code in their backends.py script on line 33 as well as install Ninja following this solution found on [issue #33](https://github.com/MrForExample/ComfyUI-3D-Pack/issues/35).

All the other workflows work after those fixes except the multi-view images to 3D.

**Comment by MrForExample** [comment]
Right, I updated that part two days ago, please update the example workflow to run it 👍

**Comment by MyNightMare** [comment]
Same error with the new workflow, there even are nodes that are not connected to anything

**Comment by MrForExample** [comment]
Apologies, I think I forgot push that part of change, it's updated now, let me know if you encounter other problem 👍

**Comment by PunishMints** [comment]
The new update works - thanks for the quick response!
