### ISSUE TITLE
failed to load 3D obj when using IP address

### ISSUE THREAD

**Issue by bbbbubble** [MrForExample/ComfyUI-3D-Pack#57]
@MrForExample Thank you for the excellent work!

I run this project on a headless server with centos system. Generally, it runs well, except for these two problems.

1. It shows the 3D object results correctly when i open the website with http://127.0.0.1:port/ or http://localhost:port/, but failed on visulaization when using http://<server_ip>:port. Could you help me with that, so I can share this website with my colleagues?
![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/45709295/2b97fad5-5f04-4fa0-b3cc-1cd1acef7d65)

2. There is also a small problem when using http://127.0.0.1:port/, It seems that the filepath of the result .obj and .mtl are wrong because of the confusion with Windows path symbol "\". 
![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/45709295/984403dd-d6e2-451d-8549-0e1e919dc400)
![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/45709295/fd8b0f2c-a593-48ea-8332-3c7db554dff1)

**Comment by MrForExample** [comment]
Oh, right, I do have a security check on the server, to only allow the reading files from Localhost, since most user use it locally:

```python
@server.PromptServer.instance.routes.get("/extensions/ComfyUI-3D-Pack/html/viewfile")
async def view_file(request):
    query = request.rel_url.query
    # Security check to see if query client is local
    if request.remote == "127.0.0.1" and "filepath" in query:
        filepath = query["filepath"]
        
        cstr(f"[Server Query view_file] Get file {filepath}").msg.print()
        
        if filepath.lower().endswith(SUPPORTED_VIEW_EXTENSIONS) and os.path.exists(filepath):
            return web.FileResponse(filepath)
    
    return web.Response(status=404)
```

You can change the "127.0.0.1" to your own IP and restart the servers.
I'll move it into a config file in the next update, cheers 👍

**Comment by bbbbubble** [comment]
> Oh, right, I do have a security check on the server, to only allow the reading files from Localhost, since most user use it locally:
> 
> ```python
> @server.PromptServer.instance.routes.get("/extensions/ComfyUI-3D-Pack/html/viewfile")
> async def view_file(request):
>     query = request.rel_url.query
>     # Security check to see if query client is local
>     if request.remote == "127.0.0.1" and "filepath" in query:
>         filepath = query["filepath"]
>         
>         cstr(f"[Server Query view_file] Get file {filepath}").msg.print()
>         
>         if filepath.lower().endswith(SUPPORTED_VIEW_EXTENSIONS) and os.path.exists(filepath):
>             return web.FileResponse(filepath)
>     
>     return web.Response(status=404)
> ```
> 
> You can change the "127.0.0.1" to your own IP and restart the servers. I'll move it into a config file in the next update, cheers 👍

Thank you for quick response!

How about the second problem, the confusion between symbol / and \, no idea how to fix that because not familiar with js...

**Comment by MrForExample** [comment]
Well, that doesn't really matter though, it will still load object correct, give a try and you'll see 👍

**Comment by MrForExample** [comment]
Hi @bbbbubble 
I updated the Comfy3D and now you can just add your client IP inside ComfyUI-3D-Pack\configs\system.conf
Cheers, have a good day 👍
