### ISSUE TITLE
Preview modules do not update automatically.

### ISSUE THREAD

**Issue by Nemess0r** [MrForExample/ComfyUI-3D-Pack#62]
Preview modules do not update automatically. When re-generating, the preview from the previous generation remains; the viewport can only be updated by refreshing the page.
![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/161450810/e5f6aa45-66ed-4adf-a2f0-73cd78793bcb)

**Comment by MrForExample** [comment]
Thanks for testing, I'm aware of this issue,  plan to fix it together with next update, likely this weekend 👍

**Comment by Nemess0r** [comment]
> Thanks for testing, I'm aware of this issue, plan to fix it together with next update, likely this weekend 👍

It would be nice if it were possible to display the mesh without a texture, as well as adjust the scene lighting in 3DPreview. Because The 3D display is now very dim, only when zooming almost to the surface does the light source become visible.

**Comment by Nemess0r** [comment]
So it would be very good if Comfy3D could become an analogue for ThreeStudio, because The Comfy interface allows for more and more flexible customization.
I'm wondering if there's any way to run ImageDream-P on your nodes

**Comment by MrForExample** [comment]
> > Thanks for testing, I'm aware of this issue, plan to fix it together with next update, likely this weekend 👍
> 
> It would be nice if it were possible to display the mesh without a texture, as well as adjust the scene lighting in 3DPreview. Because The 3D display is now very dim, only when zooming almost to the surface does the light source become visible.

That is a good idea, I'll give some thinking to that.

> So it would be very good if Comfy3D could become an analogue for ThreeStudio, because The Comfy interface allows for more and more flexible customization.
> I'm wondering if there's any way to run ImageDream-P on your nodes

I do have plan for ImageDream, should coming in next week.

**Comment by MrForExample** [comment]
Hi @Nemess0r 
I updated the Comfy3D and now this bug is fixed, pls give a try, in a rare case your preview node does not appears to be updated then please clean the browser cache
Cheers, have a good day 👍
