### ISSUE TITLE
Sir I wanna know how to use this node while i am using the embed python env

### ISSUE THREAD

**Issue by JcandZero** [MrForExample/ComfyUI-3D-Pack#7]
All site package I have downloaded are in my embeded python env. So I don't have the miniconda. I want to know that how can I use this

**Comment by MrForExample** [comment]
If you are on windows, then you can using the [install method @doctorpangloss proposed](https://github.com/MrForExample/ComfyUI-3D-Pack/issues/5)
I will add that method in the install instruction in the next update
I haven't test it though, but it use **Chocolatey** so it should work without any conceivable problem

PS: I know this is a pain for people who already installed ComfyUI with embed python env, and I really tried to make it work. But unfortunately seems I'm not experienced enough in this matter, but I'll continue to looking for the better solutions and open to any suggestions.

Cheers👍

**Comment by JcandZero** [comment]
THANKS！
