### ISSUE TITLE
Feature proposal: Normal generator for novel view synthesis

### ISSUE THREAD

**Issue by jclarkk** [MrForExample/ComfyUI-3D-Pack#73]
Hi!

Thought it might be a good idea to use a normal map generator such as this: https://github.com/baegwangbin/DSINE
For workflows that do not generate normal maps in their novel view synthesis models. Then we could leverage the NeuS workflow once they have obtained normal maps.

WDYT?

**Comment by MrForExample** [comment]
Thanks for telling me that
Yes, I'm aware of this possibility, it's in my plan to add it, cheers 👍
