### ISSUE TITLE
Mesh Preview doesn't display result when using ComfyUI remotely

### ISSUE THREAD

**Issue by FrankTrog** [MrForExample/ComfyUI-3D-Pack#82]
Thanks for putting this together by the way! 

I have a ComfyUI setup on a machine that I access remotely on the same network. When I run queue and it generates a mesh it shows nothing in the preview. Loading up the dev tools for the browser and watching the network tab it appears to be trying to view the file but failing. There are no errors in the ComfyUI log. Below is the URL it is trying to use to load the file with ip and port changed.

http://COMFYUIMACHINEIP:PORT/extensions/ComfyUI-3D-Pack/html/viewfile?filepath=C%3A%5CComfyUI_windows_portable%5CComfyUI%5Coutput%2FturtleTest.mtl
http://COMFYUIMACHINEIP:PORT/extensions/ComfyUI-3D-Pack/html/viewfile?filepath=C%3A%5CComfyUI_windows_portable%5CComfyUI%5Coutput%2FturtleTest.obj

**Comment by MrForExample** [comment]
Yeah, about that, I'll add it to the config in next update: for now you can walk around it following this issue](https://github.com/MrForExample/ComfyUI-3D-Pack/issues/57)

**Comment by FrankTrog** [comment]
Thanks. I did notice that last night but didn't get a chance to play with it until today. Confirmed changing the ip to that of my current workstation resolves it. 

What about creating a custom node that changes the ip for the request that that which is using ComfyUI?

**Comment by MrForExample** [comment]
> Thanks. I did notice that last night but didn't get a chance to play with it until today. Confirmed changing the ip to that of my current workstation resolves it.
> 
> What about creating a custom node that changes the ip for the request that that which is using ComfyUI?

I'll try to find a solution for it tomorrow, there should be some elegant to do so :) I'll let you know once it's done

**Comment by MrForExample** [comment]
Hi @FrankTrog 
I updated the Comfy3D and now you can just add your client IP inside ComfyUI-3D-Pack\configs\system.conf
Cheers, have a good day 👍
