### ISSUE TITLE
BakeTextureToMesh missing?

### ISSUE THREAD

**Issue by nistvan86** [MrForExample/ComfyUI-3D-Pack#88]
The readme mentions that the "Stack Orbit Camera Poses" functionality can be used in conjunction with BakeTextureToMesh but I don't find such node in the module. Is it in the making or existed some verisons ago but got removed ever since?

**Comment by MrForExample** [comment]
Hi friend, in case you missed:

![Screenshot 2024-03-12 231429](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/62230687/407f4257-ed22-429b-9af8-ad958db190bf)

You can also check [example workflows](https://github.com/MrForExample/ComfyUI-3D-Pack/tree/main/_Example_Workflows) for how to use it 👍
